Repository swarm-game/swarm, pull requests merged in 2021-09, with the labels that each got.

#47 Reduce framerate to ~100fps
  src/Swarm/App.hs
Labels: Z-User Experience, C-Low Hanging Fruit, S-Nice to have

#62 Further reduce maximum FPS to 30
  src/Swarm/App.hs
Labels: Z-User Experience, S-Nice to have

#81 Add mergify configuration
  .github/workflows/haskell-ci.yml
  .mergify.yml
  CONTRIBUTING.md
Labels: merge me

#87 Add entity growth rates and parameterize the `seedProgram`
  data/entities.yaml
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Pipeline/QQ.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
Labels: merge me

#72 Persist the inventory of the last robot viewed
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/TUI/Controller.hs
Labels: merge me

#83 Add Help screen
  src/Swarm/App.hs
  src/Swarm/Game/State.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/View.hs
Labels: merge me

#86 Add parser test and fix missing semicolon between defs
  src/Swarm/Language/Parse.hs
  swarm.cabal
  test/Unit.hs
Labels: merge me

#107 stack: update to latest lts-18.12 for ghc-8.10.7
  stack.yaml
Labels: merge me

#106 add `scanner` device, `scan` and `upload` commands
  TUTORIAL.md
  data/entities.yaml
  data/recipes.yaml
  images/firstrobot.png
  images/initial.png
  images/log.png
  images/mover1.png
  images/scantree.png
  images/viewtree.png
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
Labels: merge me

#105 Better handling of water
  data/entities.yaml
  data/recipes.yaml
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Terrain.hs
  src/Swarm/Game/WorldGen.hs
  src/Swarm/Language/Capability.hs
Labels: merge me

#125 TUI: Add j,k vim bindings for infopane control
  src/Swarm/TUI/List.hs
  src/Swarm/TUI/View.hs
Labels: merge me
