Repository swarm-game/swarm, pull requests merged in 2022-12, with the labels that each got.

#889 remove --cabal-default-extensions arg from fourmolu invocation
  .restyled.yaml
  CONTRIBUTING.md
  fourmolu.yaml
  scripts/reformat-code.sh
Labels: merge me

#891 Reformat all files with new Fourmolu version 0.9.0.0 standard
  src/Swarm/App.hs
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Exception.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/ScenarioInfo.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/WorldGen.hs
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Requirement.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/View.hs
  src/Swarm/Util.hs
  test/unit/TestEval.hs
  test/unit/TestPretty.hs
Labels: merge me

#898 Document the autocomplete implemented in #798
  data/scenarios/Tutorials/craft.yaml
Labels: merge me

#880 Split Scenario.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Cell.hs
  src/Swarm/Game/Scenario/RobotLookup.hs
  src/Swarm/Game/Scenario/WorldDescription.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#879 Decompose model module
  src/Swarm/App.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/Menus.hs
  src/Swarm/TUI/Model/Names.hs
  src/Swarm/TUI/Model/Repl.hs
  src/Swarm/TUI/Model/StateUpdates.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#881 Extract utils from Controller and View
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Utils.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Utils.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#900 remove log command
  data/scenarios/Tutorials/install.yaml
Labels: merge me

#895 new bind tutorial
  data/scenarios/Tutorials/00-ORDER.txt
  data/scenarios/Tutorials/bind.yaml
  data/scenarios/Tutorials/bind2-solution.sw
  data/scenarios/Tutorials/bind2.yaml
  data/scenarios/Tutorials/build.yaml
  test/integration/Main.hs
Labels: merge me

#899 show devices that enable commands
  src/Swarm/Game/Entity.hs
  src/Swarm/TUI/View.hs
  src/Swarm/Util.hs
Labels: merge me

#902 more preparation for World Editor PR
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Menus.hs
Labels: merge me

#904 blog post advertising Swarm swarm
  docs/blog/2022-swarm-swarm.md
Labels: merge me

#901 Consolidate more UI code into UI.hs
  src/Swarm/App.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Util.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/TUI/Model/Name.hs
  src/Swarm/TUI/Model/Repl.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Util.hs
  swarm.cabal
Labels: merge me

#861 Add generic construction and elimination functions for `text` type
  data/entities.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  test/unit/TestEval.hs
Labels: merge me

#887 implement Equip/Unequip
  data/entities.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/TUI/Model.hs
Labels: merge me, L-Commands

#914 Restyle main
  src/Swarm/Game/Step.hs
Labels: merge me

#919 Add new `Location` and `Heading` types, and change coordinates from 64 to 32 bits
  bench/Benchmark.hs
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Scenario/WorldDescription.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/World.hs
  src/Swarm/Game/WorldGen.hs
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Pipeline.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/View.hs
  src/Swarm/Util.hs
  src/Swarm/Util/Location.hs
  swarm.cabal
Labels: merge me

#796 achievements board
  src/Swarm/Game/Exception.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Achievement/Attainment.hs
  src/Swarm/TUI/Model/Achievement/Definitions.hs
  src/Swarm/TUI/Model/Achievement/Description.hs
  src/Swarm/TUI/Model/Achievement/Persistence.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/TUI/Model/Name.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Achievement.hs
  src/Swarm/Util.hs
  swarm.cabal
Labels: merge me

#885 A "bucket brigade" of robots
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_bucket-brigade/brigade.sw
  data/scenarios/Challenges/_bucket-brigade/hauler.sw
  data/scenarios/Challenges/_bucket-brigade/powerplant.sw
  data/scenarios/Challenges/bucket-brigade.yaml
Labels: merge me, G-Scenarios

#926 nonposession unit test
  data/scenarios/Testing/858-inventory/00-ORDER.txt
  data/scenarios/Testing/858-inventory/858-nonpossession-objective.yaml
  test/integration/Main.hs
Labels: merge me

#925 first tutorial completion achievement
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/StateUpdate.hs
Labels: merge me, G-Achievements

#903 Parameterize scenario datatypes
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Cell.hs
  src/Swarm/Game/Scenario/WorldDescription.hs
Labels: merge me

#929 Split Objective into its own module
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Objective.hs
  swarm.cabal
Labels: merge me

#930 Remove superfluous re-exports
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Util.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Util.hs
  src/Swarm/Web.hs
Labels: merge me

#920 Meeting other robots
  data/entities.yaml
  data/recipes.yaml
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_friend/cat.sw
  data/scenarios/Challenges/_friend/friend-solution.sw
  data/scenarios/Challenges/friend.yaml
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/920-meet.yaml
  data/scenarios/Tutorials/crash-secret.sw
  data/scenarios/Tutorials/farming.sw
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  example/BFS-clear.sw
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/Language/Types.hs
  test/integration/Main.hs
Labels: merge me
