Repository swarm-game/swarm, pull requests merged in 2023-12, with the labels that each got.

#1670 Inherit parent robot display
  src/Swarm/Game/Step/Const.hs
Labels: T-UI, merge me

#1675 split utils into sublibrary
  src/swarm-util/Control/Carrier/Accum/FixedStrict.hs
  src/swarm-util/Data/BoolExpr/Simplify.hs
  src/swarm-util/Swarm/Util.hs
  src/swarm-util/Swarm/Util/Erasable.hs
  src/swarm-util/Swarm/Util/Lens.hs
  src/swarm-util/Swarm/Util/Parse.hs
  src/swarm-util/Swarm/Util/RingBuffer.hs
  src/swarm-util/Swarm/Util/UnitInterval.hs
  src/swarm-util/Swarm/Util/WindowedCounter.hs
  src/swarm-util/Swarm/Util/Yaml.hs
  swarm.cabal
Labels: merge me

#1674 use strictly background color for terrain
  src/Swarm/App.hs
  src/Swarm/Game/Display.hs
  src/Swarm/Game/Entity/Cosmetic/Assignment.hs
  src/Swarm/Game/Terrain.hs
  src/Swarm/Game/World/Render.hs
  src/Swarm/TUI/View/Attribute/Attr.hs
Labels: merge me

#1677 Inventory requirements for child robots of system robots
  data/scenarios/Testing/201-require/00-ORDER.txt
  data/scenarios/Testing/201-require/1664-require-system-robot-children.yaml
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#1682 Specifically build `swarm:swarm` component in `play.sh` script
  scripts/play.sh
Labels: merge me

#1678 recognize structures with rotation
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/Ranching/beekeeping.yaml
  data/scenarios/Challenges/_pack-tetrominoes/solution.sw
  data/scenarios/Challenges/pack-tetrominoes.yaml
  data/scenarios/Testing/1575-structure-recognizer/00-ORDER.txt
  data/scenarios/Testing/1575-structure-recognizer/1575-bounding-box-overlap.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-browse-structures.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-construction-count.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-ensure-disjoint.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-ensure-single-recognition.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-floorplan-command.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-handle-overlapping.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-interior-entity-placement.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-nested-structure-definition.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-overlapping-tiebreaker-by-largest.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-overlapping-tiebreaker-by-location.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-placement-occlusion.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-remove-structure.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-swap-structure.yaml
  data/scenarios/Testing/1575-structure-recognizer/1644-rotated-preplacement-recognition.yaml
  data/scenarios/Testing/1575-structure-recognizer/1644-rotated-recognition.yaml
  data/scenarios/Testing/_Validation/1575-recognized-placements-disallow-reorientation.yaml
  data/scenarios/Testing/_Validation/1678-redundant-structure-recognition-symmetries.yaml
  data/schema/directions.json
  data/schema/named-structure.json
  data/schema/structure-orient.json
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Topography/Structure.hs
  src/Swarm/Game/Scenario/Topography/Structure/Recognition/Log.hs
  src/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/Swarm/Game/Scenario/Topography/Structure/Recognition/Symmetry.hs
  src/Swarm/Game/Scenario/Topography/Structure/Recognition/Type.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step/Const.hs
  src/Swarm/Language/Direction.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Structure.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me, G-Scenarios

#1683 pushable property
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1681-pushable-entity.yaml
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Step/Const.hs
  src/Swarm/TUI/View.hs
  test/integration/Main.hs
Labels: merge me

#1686 dim sum restaurant
  data/entities.yaml
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_dimsum/cook.sw
  data/scenarios/Challenges/_dimsum/patron.sw
  data/scenarios/Challenges/_dimsum/solution.sw
  data/scenarios/Challenges/dimsum.yaml
  src/Swarm/Game/Step/Const.hs
  test/integration/Main.hs
Labels: merge me, G-Scenarios

#1690 short module descriptions
  src/Swarm/App.hs
  src/Swarm/Constant.hs
  src/Swarm/Doc/Keyword.hs
  src/Swarm/Doc/Pedagogy.hs
  src/Swarm/Doc/Util.hs
  src/Swarm/Effect.hs
  src/Swarm/Effect/Time.hs
  src/Swarm/Game/Achievement/Attainment.hs
  src/Swarm/Game/Achievement/Definitions.hs
  src/Swarm/Game/Achievement/Description.hs
  src/Swarm/Game/Achievement/Persistence.hs
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Display.hs
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Location.hs
  src/Swarm/Game/Recipe.hs
  src/Swarm/Game/ResourceLoading.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Objective.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Step/Const.hs
  src/Swarm/Game/World.hs
Labels: Z-Documentation, merge me

#1650 demo pixi.js
  src/Swarm/Game/Scenario/Topography/Center.hs
  src/Swarm/Game/World/Render.hs
  src/Swarm/TUI/View.hs
  src/Swarm/Web.hs
  src/Swarm/Web/Worldview.hs
  src/swarm-util/Swarm/Util/OccurrenceEncoder.hs
  swarm.cabal
  web/index.html
  web/play.html
  web/script/display.js
  web/script/fetch.js
Labels: merge me

#1698 return distance from path command
  data/scenarios/Fun/horton.yaml
  data/scenarios/Testing/1569-pathfinding-cache/1569-harvest-batch.yaml
  data/scenarios/Testing/836-pathfinding/_836-automatic-waypoint-navigation/patrol.sw
  data/scenarios/Testing/836-pathfinding/_836-path-exists/find-entity-solution.sw
  data/scenarios/Testing/836-pathfinding/_836-path-exists/find-entity-unwalkable-solution.sw
  data/scenarios/Testing/836-pathfinding/_836-path-exists/find-location-solution.sw
  src/Swarm/Game/Step/Path/Finding.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
Labels: merge me
