Repository swarm-game/swarm, pull requests merged in 2023-11, with the labels that each got.

#1606 0.5 release
  CHANGELOG.md
  swarm.cabal
Labels: merge me

#1613 indicate whether a goal is optional
  src/Swarm/TUI/View/Attribute/Attr.hs
  src/Swarm/TUI/View/Objective.hs
Labels: T-UI, merge me

#1614 Extract pure walkability logic
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Step/Path/Walkability.hs
  src/Swarm/Game/Step/Util.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#1615 use `mkReturn` in more places
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Value.hs
Labels: merge me

#1610 Fix REPL type display
  src/Swarm/TUI/Panel.hs
  src/Swarm/TUI/View/Util.hs
Labels: merge me, CHANGELOG

#1619 Don't auto-complete commands that require God capability outside creative mode
  src/Swarm/TUI/Controller.hs
Labels: merge me

#1618 structure recognition enhancements
  data/entities.yaml
  data/scenarios/Testing/1575-structure-recognizer/00-ORDER.txt
  data/scenarios/Testing/1575-structure-recognizer/1575-browse-structures.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-construction-count.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-ensure-disjoint.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-ensure-single-recognition.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-floorplan-command.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-handle-overlapping.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-interior-entity-placement.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-nested-structure-definition.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-overlapping-tiebreaker-by-location.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-placement-occlusion.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-remove-structure.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-swap-structure.yaml
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/Swarm/Game/Scenario/Topography/Structure/Recognition/Type.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Value.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/View/Structure.hs
  src/Swarm/TUI/View/Util.hs
  test/integration/Main.hs
Labels: merge me, L-Commands

#1617 Update to support running on Windows
  src/Swarm/App.hs
  swarm.cabal
Labels: merge me, CHANGELOG

#1595 path caching
  data/scenarios/Fun/00-ORDER.txt
  data/scenarios/Fun/horton.yaml
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1569-pathfinding-cache/00-ORDER.txt
  data/scenarios/Testing/1569-pathfinding-cache/1569-cache-invalidation-distance-limit.yaml
  data/scenarios/Testing/1569-pathfinding-cache/1569-cache-invalidation-modes.yaml
  data/scenarios/Testing/1569-pathfinding-cache/1569-harvest-batch.yaml
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Step/Combustion.hs
  src/Swarm/Game/Step/Path/Cache.hs
  src/Swarm/Game/Step/Path/Cache/DistanceLimit.hs
  src/Swarm/Game/Step/Path/Finding.hs
  src/Swarm/Game/Step/Path/Type.hs
  src/Swarm/Game/Step/RobotStepState.hs
  src/Swarm/Game/Step/Util.hs
  src/Swarm/Game/Step/Util/Inspect.hs
  src/Swarm/Game/World/Modify.hs
  src/Swarm/Util.hs
  src/Swarm/Util/RingBuffer.hs
  src/Swarm/Web.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me, L-Commands, Z-Performance, CHANGELOG

#1627 Fix the stack build
  stack.yaml
Labels: merge me

#1620 Add TimeEffect effect for getting current time
  src/Swarm/Effect.hs
  src/Swarm/Effect/Time.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Step/Combustion.hs
  src/Swarm/Game/Step/Util.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/Util/Effect.hs
  swarm.cabal
  test/bench/Benchmark.hs
  test/integration/Main.hs
  test/unit/TestUtil.hs
Labels: merge me

#1629 achievement for giving to self
  src/Swarm/Game/Achievement/Definitions.hs
  src/Swarm/Game/Achievement/Description.hs
  src/Swarm/Game/Step.hs
Labels: merge me

#1634 Decouple robot log message colors from entity colors
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1634-message-colors.yaml
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Attribute/Attr.hs
Labels: merge me

#1635 Implement entity tags and commands
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1631-tags.yaml
  data/schema/entity.json
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/TUI/View/CellDisplay.hs
  src/Swarm/TUI/View/Util.hs
  test/integration/Main.hs
Labels: merge me

#1637 Structure recognition with encroaching entities
  data/scenarios/Testing/1575-structure-recognizer/00-ORDER.txt
  data/scenarios/Testing/1575-structure-recognizer/1575-bounding-box-overlap.yaml
  src/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/Swarm/Game/Scenario/Topography/Structure/Recognition/Tracking.hs
  src/Swarm/Game/Scenario/Topography/Structure/Recognition/Type.hs
  test/integration/Main.hs
Labels: merge me

#1632 render map to PNG format
  app/Main.hs
  data/scenarios/Testing/1034-custom-attributes.yaml
  data/scenarios/Testing/_Validation/1632-entity-attributes.yaml
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Entity/Cosmetic.hs
  src/Swarm/Game/Entity/Cosmetic/Assignment.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Status.hs
  src/Swarm/Game/Scenario/Style.hs
  src/Swarm/Game/Scenario/Topography/Center.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/World/Render.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Attribute/Attr.hs
  src/Swarm/TUI/View/Attribute/CustomStyling.hs
  src/Swarm/TUI/View/Attribute/Util.hs
  src/Swarm/TUI/View/Logo.hs
  swarm.cabal
Labels: merge me, CHANGELOG

#1640 split cheatsheet generation to separate module
  src/Swarm/Doc/Gen.hs
  src/Swarm/Doc/Util.hs
  src/Swarm/Doc/Wiki/Cheatsheet.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#1646 render recognized structures in bold
  data/scenarios/Testing/1575-structure-recognizer/1575-ensure-disjoint.yaml
  src/Swarm/TUI/View/CellDisplay.hs
Labels: merge me

#1648 serve static index page
  src/Swarm/Web.hs
  swarm.cabal
  web/index.html
Labels: merge me, T-Web

#1652 group robot info into subrecord
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Step/Util.hs
  src/Swarm/Game/Step/Util/Inspect.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Util.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/CellDisplay.hs
  src/Swarm/Web.hs
  test/integration/Main.hs
  test/unit/TestNotification.hs
  test/unit/TestUtil.hs
Labels: Z-Refactoring, merge me

#1651 use built-in portal functionality for Hackman scenario
  data/scenarios/Challenges/_hackman/ghost.sw
  data/scenarios/Challenges/_hackman/solution.sw
  data/scenarios/Challenges/_hackman/teleport_monitor.sw
  data/scenarios/Challenges/_hackman/teleporter.sw
  data/scenarios/Challenges/hackman.yaml
Labels: merge me, G-Scenarios

#1655 validate display character widths
  data/scenarios/Challenges/Ranching/gated-paddock.yaml
  data/scenarios/Testing/_Validation/1655-display-characters.yaml
  src/Swarm/Game/Display.hs
Labels: merge me

#1653 dedicated record for randomness
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step/Util.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Util.hs
Labels: merge me

#1656 Use a nonempty list for unchainFun
  src/Swarm/Language/Pretty.hs
Labels: merge me

#1599 beekeeping scenario
  data/entities.yaml
  data/scenarios/Challenges/Ranching/00-ORDER.txt
  data/scenarios/Challenges/Ranching/_beekeeping/queenbee.sw
  data/scenarios/Challenges/Ranching/_beekeeping/solution.sw
  data/scenarios/Challenges/Ranching/beekeeping.yaml
  test/integration/Main.hs
Labels: merge me, T-Challenges, CHANGELOG

#1665 Split `Step.hs`
  scripts/benchmark-against-parent.sh
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Step/Arithmetic.hs
  src/Swarm/Game/Step/Const.hs
  src/Swarm/Game/Step/Util/Command.hs
  swarm.cabal
Labels: Z-Refactoring, merge me, CHANGELOG
