Repository swarm-game/swarm, pull requests merged in 2023-10, with the labels that each got.

#1556 robot wave scenario
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_wave/solution.sw
  data/scenarios/Challenges/wave.yaml
  test/integration/Main.hs
Labels: merge me, G-Scenarios, CHANGELOG

#1562 Limit system robot activity tracking
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Step.hs
Labels: merge me

#1491 use Int64 for time
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Step.hs
Labels: merge me

#1564 more partial function bans
  .hlint.yaml
  src/Swarm/Doc/Gen.hs
  src/Swarm/Game/Achievement/Attainment.hs
  src/Swarm/Game/Location.hs
  src/Swarm/Game/ResourceLoading.hs
  src/Swarm/Language/Key.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/Util.hs
Labels: merge me

#1566 Restore the "classic world" background for `friend` challenge
  data/scenarios/Challenges/friend.yaml
  data/scenarios/Challenges/gopher.yaml
Labels: merge me

#1479 Make function chains pretty
  scripts/compare-format.sh
  src/Swarm/Language/Pretty.hs
  src/Swarm/Util.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1577 command types on one line
  src/Swarm/TUI/View.hs
Labels: T-UI, merge me

#1441 Autogenerate scenario schema doc
  app/Main.hs
  data/scenarios/README.md
  data/scenarios/doc-fragments/SCHEMA.md
  data/scenarios/doc-fragments/base-robot.md
  data/scenarios/doc-fragments/capabilities.md
  data/scenarios/doc-fragments/cells.md
  data/scenarios/doc-fragments/entity-properties.md
  data/scenarios/doc-fragments/header.md
  data/schema/attribute.json
  data/schema/combustion.json
  data/schema/cosmic-loc.json
  data/schema/display.json
  data/schema/entities.json
  data/schema/entity-count.json
  data/schema/entity.json
  data/schema/explicit-waypoint.json
  data/schema/inventory.json
  data/schema/named-structure.json
  data/schema/objective.json
  data/schema/orientation-map.json
  data/schema/placement.json
  data/schema/portal-exit.json
  data/schema/portal.json
  data/schema/prerequisite.json
  data/schema/range.json
  data/schema/recipe.json
  data/schema/recipes.json
  data/schema/robot.json
  data/schema/scenario.json
  data/schema/structure-orient.json
  data/schema/structure.json
  data/schema/world.json
  scripts/regenerate-schema-docs.sh
  src/Swarm/Doc/Gen.hs
  src/Swarm/Doc/Schema/Arrangement.hs
  src/Swarm/Doc/Schema/Parse.hs
  src/Swarm/Doc/Schema/Refined.hs
  src/Swarm/Doc/Schema/Render.hs
  src/Swarm/Doc/Schema/SchemaType.hs
  src/Swarm/Doc/Util.hs
  swarm.cabal
Labels: merge me

#1576 Add wave program to benchmarks
  scripts/reformat-code.sh
  swarm.cabal
  test/bench/Benchmark.hs
Labels: merge me

#1586 Account for symlink when applying JSON schemas
  .vscode/settings.json
Labels: merge me, Z-Developer Experience

#1591 combination locks scenario
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_combo-lock/setup.sw
  data/scenarios/Challenges/_combo-lock/solution.sw
  data/scenarios/Challenges/combo-lock.yaml
  test/integration/Main.hs
Labels: merge me, G-Scenarios

#1588 Achievement for pointless swapping
  src/Swarm/Game/Achievement/Definitions.hs
  src/Swarm/Game/Achievement/Description.hs
  src/Swarm/Game/Step.hs
Labels: merge me, G-Achievements

#1604 Use rich entity modification info
  src/Swarm/Game/Step/Util.hs
  src/Swarm/Game/World.hs
  src/Swarm/Game/World/Modify.hs
  swarm.cabal
Labels: merge me
