Repository swarm-game/swarm, pull requests merged in 2023-06, with the labels that each got.

#1296 Density command
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1295-density-command.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  test/integration/Main.hs
Labels: merge me

#1298 Better type error messages
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Typecheck.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1299 Cleanup 'use' command code
  data/scenarios/Testing/1007-use-command.yaml
  src/Swarm/Game/Step.hs
Labels: merge me

#1305 ensure progress gets saved
  src/Swarm/TUI/Model/StateUpdate.hs
Labels: Bug, merge me

#1311 peg fourmolu version
  .restyled.yaml
  CONTRIBUTING.md
  fourmolu.yaml
Labels: merge me, Z-Meta

#1010 Scenario launch options selection
  src/Swarm/Game/Scenario/Status.hs
  src/Swarm/Game/State.hs
  src/Swarm/TUI/Attr.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Launch/Controller.hs
  src/Swarm/TUI/Launch/Model.hs
  src/Swarm/TUI/Launch/Prep.hs
  src/Swarm/TUI/Launch/View.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/TUI/Model/Name.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Objective.hs
  src/Swarm/TUI/View/Util.hs
  swarm.cabal
Labels: merge me

#1315 Make launch options message take up a whole line, even when blank
  src/Swarm/TUI/View.hs
Labels: merge me

#873 world editor prototype
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Cell.hs
  src/Swarm/Game/Scenario/EntityFacade.hs
  src/Swarm/Game/Scenario/WorldDescription.hs
  src/Swarm/Game/Scenario/WorldPalette.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Terrain.hs
  src/Swarm/Game/World.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Util.hs
  src/Swarm/TUI/Editor/Area.hs
  src/Swarm/TUI/Editor/Controller.hs
  src/Swarm/TUI/Editor/Json.hs
  src/Swarm/TUI/Editor/Masking.hs
  src/Swarm/TUI/Editor/Model.hs
  src/Swarm/TUI/Editor/Palette.hs
  src/Swarm/TUI/Editor/Util.hs
  src/Swarm/TUI/Editor/View.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/TUI/Model/Name.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/CellDisplay.hs
  src/Swarm/TUI/View/Util.hs
  src/Swarm/Util.hs
  swarm.cabal
Labels: merge me

#1322 Don't step robots that are waiting, even during `instant`
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Step.hs
Labels: merge me

#1308 More typechecking error message improvements
  src/Swarm/Language/LSP.hs
  src/Swarm/Language/Pipeline.hs
  src/Swarm/Language/Pipeline/QQ.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/Language/Typecheck/Unify.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1330 wrap TickNumber in newtype
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Scenario/Scoring/ConcreteMetrics.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/CellDisplay.hs
  test/integration/Main.hs
  test/unit/TestNotification.hs
  test/unit/TestScoring.hs
Labels: Z-Refactoring, merge me

#1318 Better type error messages when there are unification variables involved
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Typecheck.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1332 structure templates
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1138-structures/00-ORDER.txt
  data/scenarios/Testing/1138-structures/flip-and-rotate.yaml
  data/scenarios/Testing/1138-structures/nested-structure.yaml
  data/scenarios/Testing/1138-structures/sibling-precedence.yaml
  src/Swarm/Game/Scenario/Structure.hs
  src/Swarm/Game/Scenario/WorldDescription.hs
  swarm.cabal
Labels: merge me

#1334 traffic vignette
  data/scenarios/00-ORDER.txt
  data/scenarios/Vignettes/00-ORDER.txt
  data/scenarios/Vignettes/_roadway/coordinator.sw
  data/scenarios/Vignettes/_roadway/drone.sw
  data/scenarios/Vignettes/roadway.yaml
Labels: merge me

#976 active trapdoor demo
  data/scenarios/00-ORDER.txt
  data/scenarios/Mechanics/00-ORDER.txt
  data/scenarios/Mechanics/_active-trapdoor/gate.sw
  data/scenarios/Mechanics/_active-trapdoor/solution.sw
  data/scenarios/Mechanics/active-trapdoor.yaml
  test/integration/Main.hs
Labels: merge me

#1237 sliding puzzle
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/Sliding Puzzles/00-ORDER.txt
  data/scenarios/Challenges/Sliding Puzzles/3x3.yaml
  data/scenarios/Challenges/Sliding Puzzles/_sliding-puzzle/design-commentary.md
  data/scenarios/Challenges/Sliding Puzzles/_sliding-puzzle/maintainer.sw
  data/scenarios/Challenges/Sliding Puzzles/_sliding-puzzle/setup.sw
  data/scenarios/Challenges/Sliding Puzzles/_sliding-puzzle/solution.sw
  data/scenarios/Challenges/Sliding Puzzles/_sliding-puzzle/validate-board.sw
  scripts/play.sh
  src/Swarm/TUI/Controller.hs
  test/integration/Main.hs
Labels: merge me

#1337 canonical device for 'scout' command
  data/entities.yaml
  data/scenarios/Testing/1207-scout-command.yaml
Labels: merge me

#971 scenario with enemies
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_blender/apprehension-checker.sw
  data/scenarios/Challenges/_blender/patrol-clockwise.sw
  data/scenarios/Challenges/_blender/patrol-counter-clockwise.sw
  data/scenarios/Challenges/_blender/solution.sw
  data/scenarios/Challenges/blender.yaml
  test/integration/Main.hs
Labels: merge me

#1192 arbitrage scenario
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_arbitrage/design-notes.md
  data/scenarios/Challenges/_arbitrage/solution.sw
  data/scenarios/Challenges/arbitrage.yaml
  test/integration/Main.hs
Labels: merge me

#1339 Separate entities for each text operation
  data/entities.yaml
  src/Swarm/Language/Capability.hs
Labels: merge me

#1346 rename inventory to compendium
  src/Swarm/TUI/Model.hs
Labels: merge me

#1344 goal dialog suppression with --autoplay
  src/Swarm/Game/State.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Launch/Model.hs
  src/Swarm/TUI/Launch/Prep.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
Labels: merge me

#1342 powerset scenario
  data/scenarios/Challenges/Ranching/00-ORDER.txt
  data/scenarios/Challenges/Ranching/_powerset/setup.sw
  data/scenarios/Challenges/Ranching/_powerset/solution.sw
  data/scenarios/Challenges/Ranching/powerset.yaml
  test/integration/Main.hs
Labels: merge me, G-Scenarios

#1351 Update to LTS-21, GHC 9.4.5, brick-1.9
  stack.yaml
  swarm.cabal
Labels: merge me
