Repository swarm-game/swarm, pull requests merged in 2023-08, with the labels that each got.

#1400 Implement 'backup' command
  data/entities.yaml
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1399-backup-command.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  test/integration/Main.hs
Labels: merge me

#1106 Parse markdown descriptions
  data/entities.yaml
  data/scenarios/Challenges/Mazes/easy_spiral_maze.yaml
  data/scenarios/Challenges/Mazes/invisible_maze.yaml
  data/scenarios/Challenges/Mazes/loopy_maze.yaml
  data/scenarios/Challenges/arbitrage.yaml
  data/scenarios/Tutorials/backstory.yaml
  data/scenarios/Tutorials/bind2.yaml
  data/scenarios/Tutorials/build.yaml
  data/scenarios/Tutorials/conditionals.yaml
  data/scenarios/Tutorials/craft.yaml
  data/scenarios/Tutorials/crash.yaml
  data/scenarios/Tutorials/def.yaml
  data/scenarios/Tutorials/equip.yaml
  data/scenarios/Tutorials/farming.yaml
  data/scenarios/Tutorials/grab.yaml
  data/scenarios/Tutorials/lambda.yaml
  data/scenarios/Tutorials/move.yaml
  data/scenarios/Tutorials/place.yaml
  data/scenarios/Tutorials/require.yaml
  data/scenarios/Tutorials/requireinv.yaml
  data/scenarios/Tutorials/scan.yaml
  data/scenarios/Tutorials/type-errors.yaml
  data/scenarios/Tutorials/types.yaml
  data/scenarios/Tutorials/world101.yaml
  src/Swarm/Doc/Gen.hs
  src/Swarm/Doc/Pedagogy.hs
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Failure.hs
  src/Swarm/Game/Failure/Render.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Objective.hs
  src/Swarm/Language/Text/Markdown.hs
  src/Swarm/TUI/Attr.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View/Objective.hs
  src/Swarm/TUI/View/Util.hs
  src/Swarm/Web.hs
  swarm.cabal
Labels: merge me

#1404 mention `drill` command in drill entity description
  data/entities.yaml
Labels: merge me

#1392 Refactor to more consistently use "capability style" in loading + initializing code
  src/Control/Carrier/Accum/FixedStrict.hs
  src/Swarm/App.hs
  src/Swarm/Doc/Gen.hs
  src/Swarm/Doc/Pedagogy.hs
  src/Swarm/Game/Achievement/Persistence.hs
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Exception.hs
  src/Swarm/Game/Failure.hs
  src/Swarm/Game/Recipe.hs
  src/Swarm/Game/ResourceLoading.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/ScenarioInfo.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Pipeline.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/TUI/Launch/Model.hs
  src/Swarm/TUI/Launch/Prep.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  src/Swarm/Util.hs
  src/Swarm/Util/Effect.hs
  src/Swarm/Web.hs
  swarm.cabal
  test/integration/Main.hs
  test/unit/TestScoring.hs
Labels: merge me

#1418 Throw an error instead of crashing on impredicative types
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/Language/Types.hs
Labels: merge me

#1413 Render markdown in entity descriptions
  bench/Benchmark.hs
  data/entities.yaml
  data/scenarios/Tutorials/craft.yaml
  scripts/autoplay-tutorials.sh
  src/Swarm/Doc/Gen.hs
  src/Swarm/Doc/Pedagogy.hs
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Exception.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Scenario/Objective.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Text/Markdown.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Objective.hs
  src/Swarm/TUI/View/Util.hs
  test/unit/TestInventory.hs
Labels: merge me

#1425 Refactor mystery baton type
  src/Swarm/Web.hs
Labels: merge me

#1412 add more markup to tutorial objectives prose
  data/entities.yaml
  data/scenarios/Challenges/Ranching/gated-paddock.yaml
  data/scenarios/Tutorials/bind2.yaml
  data/scenarios/Tutorials/build.yaml
  data/scenarios/Tutorials/conditionals.yaml
  data/scenarios/Tutorials/craft.yaml
  data/scenarios/Tutorials/def.yaml
  data/scenarios/Tutorials/equip.yaml
  data/scenarios/Tutorials/farming.yaml
  data/scenarios/Tutorials/grab.yaml
  data/scenarios/Tutorials/lambda.yaml
  data/scenarios/Tutorials/move.yaml
  data/scenarios/Tutorials/place.yaml
  data/scenarios/Tutorials/require.yaml
  data/scenarios/Tutorials/requireinv.yaml
  data/scenarios/Tutorials/scan.yaml
  data/scenarios/Tutorials/type-errors.yaml
  data/scenarios/Tutorials/types.yaml
  data/scenarios/Tutorials/world101.yaml
Labels: merge me

#1321 0.4 release
  CHANGELOG.md
  swarm.cabal
Labels: merge me

#1431 system robots should build system robots
  data/scenarios/Testing/1430-built-robot-ownership.yaml
  src/Swarm/Game/Step.hs
Labels: merge me

#1434 Add a pull request template
  pull_request_template.md
Labels: merge me

#1432 combustion
  data/entities.yaml
  data/scenarios/README.md
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1355-combustion.yaml
  data/schema/combustion.json
  data/schema/entities.json
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Scenario/Topography/EntityFacade.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Step/Combustion.hs
  src/Swarm/Game/Step/Util.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/TUI/Editor/Model.hs
  src/Swarm/TUI/Editor/Palette.hs
  src/Swarm/TUI/View.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#1439 various documentation improvements
  src/Swarm/Doc/Pedagogy.hs
  src/Swarm/Game/Achievement/Persistence.hs
  src/Swarm/Game/Scenario/Objective.hs
  src/Swarm/Game/Scenario/Objective/Validation.hs
  src/Swarm/Game/Scenario/Scoring/Best.hs
  src/Swarm/Game/Scenario/Scoring/CodeSize.hs
  src/Swarm/Game/Scenario/Scoring/ConcreteMetrics.hs
  src/Swarm/Game/Scenario/Scoring/GenericMetrics.hs
  src/Swarm/Game/Scenario/Status.hs
  src/Swarm/Game/Scenario/Style.hs
  src/Swarm/Game/Scenario/Topography/Area.hs
  src/Swarm/Game/Scenario/Topography/Cell.hs
  src/Swarm/Game/Scenario/Topography/EntityFacade.hs
  src/Swarm/Game/Scenario/Topography/Navigation/Portal.hs
  src/Swarm/Game/Scenario/Topography/Placement.hs
  src/Swarm/Game/Scenario/Topography/Structure.hs
  src/Swarm/Game/Universe.hs
  src/Swarm/Game/Value.hs
  src/Swarm/Game/World/Coords.hs
  src/Swarm/Language/Direction.hs
  src/Swarm/Language/LSP/Hover.hs
  src/Swarm/ReadableIORef.hs
  src/Swarm/TUI/Editor/Controller.hs
  src/Swarm/TUI/Editor/Json.hs
  src/Swarm/TUI/Editor/Masking.hs
  src/Swarm/TUI/Editor/Model.hs
  src/Swarm/TUI/Editor/Util.hs
  src/Swarm/TUI/Editor/View.hs
  src/Swarm/TUI/Launch/Controller.hs
  src/Swarm/TUI/Launch/Prep.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/TUI/Model/Name.hs
Labels: merge me

#1444 0.4 release blog post
  docs/blog/2023-08-swarm-0.4-release.md
  images/crafting.png
  images/debugger.png
  images/excursion.png
  images/scenario-launch.png
  swarm.cabal
Labels: merge me

#1445 Update metadata after publishing latest blog post
  docs/blog/.BlogLiterately-uploaded-images
  docs/blog/2023-08-swarm-0.4-release.md
Labels: merge me

#1448 Normalise versions for comparison
  src/Swarm/Version.hs
Labels: merge me

#1447 Add changelog for VSCode plugin 0.0.9
  editors/vscode/CHANGELOG.md
  editors/vscode/package.json
Labels: merge me

#1463 fix `PrettyPrec Entry` instance
  src/Swarm/Game/Failure.hs
Labels: merge me

#1460 Erase the erase function
  src/Swarm/Language/Syntax.hs
Labels: merge me

#1464 Make pretty Terms format prettier
  data/entities.yaml
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Text/Markdown.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me, CHANGELOG

#1457 Test runtime log does not contain errors
  src/Swarm/Game/Achievement/Persistence.hs
  test/integration/Main.hs
Labels: merge me

#1470 Fix lambda precedence
  src/Swarm/Language/Pretty.hs
  test/unit/TestPretty.hs
Labels: merge me

#1472 Move traversable documentation to derived instance
  src/Swarm/Language/Syntax.hs
Labels: merge me

#1459 Make CLI format format
  app/Main.hs
Labels: merge me, CHANGELOG

#1475 Validate scenarios against json schema
  .github/workflows/scenario-schema.yml
  data/scenarios/Challenges/Ranching/gated-paddock.yaml
  data/scenarios/Testing/_Validation/1221-duplicate-entities.yaml
  data/schema/attribute.json
  data/schema/combustion.json
  data/schema/cosmic-loc.json
  data/schema/display.json
  data/schema/entities.json
  data/schema/explicit-waypoint.json
  data/schema/objective.json
  data/schema/placement.json
  data/schema/planar-loc.json
  data/schema/portal.json
  data/schema/recipes.json
  data/schema/robot.json
  data/schema/scenario.json
  data/schema/structure.json
  data/schema/world.json
  editors/README.md
  scripts/validate-json-schemas.sh
Labels: merge me, Z-CI

#1477 Publish VSCode extension under swarm-game everywhere
  .github/workflows/vscode-publish.yml
  editors/README.md
  editors/vscode/CHANGELOG.md
  editors/vscode/client/package.json
  editors/vscode/package.json
Labels: merge me

#1476 Allow specific format width
  app/Main.hs
  swarm.cabal
Labels: merge me

#1478 Include VS Code workspace settings in repo
  .vscode/settings.json
  editors/README.md
Labels: merge me, Z-Developer Experience

#1482 Show robot IDs
  src/Swarm/TUI/View.hs
Labels: merge me
