Repository swarm-game/swarm, pull requests merged in 2023-04, with the labels that each got.

#1188 introduce boolexpr package to replace vendored module
  src/Data/BoolExpr.hs
  src/Swarm/Game/Scenario/Objective/WinCheck.hs
  stack.yaml
  swarm.cabal
Labels: merge me

#1193 Simplify skippable list api
  src/Brick/Widget/List/Skippable.hs
  src/Swarm/TUI/List.hs
  swarm.cabal
Labels: merge me

#1194 Pedagogy separate refactoring
  data/scenarios/Tutorials/bind2-solution.sw
  data/scenarios/Tutorials/bind2.yaml
  data/scenarios/Tutorials/crash-solution.sw
  data/scenarios/Tutorials/crash.yaml
  src/Swarm/DocGen.hs
  src/Swarm/Game/ScenarioInfo.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/World.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/Util.hs
Labels: merge me

#1196 fix inversion bug with skippable list refactor
  src/Brick/Widget/List/Skippable.hs
Labels: merge me

#1190 prefer dots over dollars
  .hlint.yaml
  src/Data/BoolExpr/Simplify.hs
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Recipe.hs
  src/Swarm/Game/ResourceLoading.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/ScenarioInfo.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/LSP.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Achievement.hs
  src/Swarm/TUI/View/Objective.hs
  src/Swarm/TUI/View/Util.hs
  test/unit/TestBoolExpr.hs
  test/unit/TestLSP.hs
  test/unit/TestLanguagePipeline.hs
  test/unit/TestPretty.hs
Labels: Z-Refactoring, merge me

#1183 `requirements` command for viewing requirements of any expression
  data/scenarios/Tutorials/require.yaml
  src/Swarm/Game/Step.hs
  src/Swarm/Language/LSP/Hover.hs
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Requirement.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/Language/Value.hs
  src/Swarm/Util.hs
  test/unit/Main.hs
Labels: merge me

#1186 Dump a list of tutorials and commands they first introduce
  app/Main.hs
  data/scenarios/Tutorials/backstory.yaml
  data/scenarios/Tutorials/build.yaml
  data/scenarios/Tutorials/crash.yaml
  data/scenarios/Tutorials/equip.yaml
  src/Swarm/Constant.hs
  src/Swarm/Doc/Gen.hs
  src/Swarm/Doc/Pedagogy.hs
  src/Swarm/Game/Exception.hs
  src/Swarm/Game/State.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/TUI/View.hs
  swarm.cabal
  test/integration/Main.hs
  test/unit/Main.hs
  test/unit/TestPedagogy.hs
Labels: merge me

#825 Autogenerate web api docs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Scenario/Objective.hs
  src/Swarm/Game/Scenario/Objective/Graph.hs
  src/Swarm/Game/Scenario/Objective/WinCheck.hs
  src/Swarm/Game/State.hs
  src/Swarm/TUI/Model/Goal.hs
  src/Swarm/TUI/Model/Repl.hs
  src/Swarm/Web.hs
  stack.yaml
  swarm.cabal
Labels: merge me

#1204 resonate command
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1171-resonate-command.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Value.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/Util.hs
Labels: merge me

#1211 use brick-list-skip package
  src/Brick/Widget/List/Skippable.hs
  src/Swarm/TUI/List.hs
  stack.yaml
  swarm.cabal
Labels: merge me

#1213 Fix `brick-list-skip` versions
  stack.yaml
  swarm.cabal
Labels: merge me

#1201 Implement 'watch' and 'surveil'
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/687-watch-command.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Log.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/ScenarioInfo.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/World.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/TUI/View.hs
Labels: merge me

#1215 Fix objective management upon goal condition exception
  src/Swarm/Game/Step.hs
  src/Swarm/TUI/Controller.hs
Labels: merge me

#1209 scout command
  data/entities.yaml
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1207-scout-command.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Value.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/TUI/View.hs
  test/integration/Main.hs
Labels: merge me

#1217 add integration test for 'resonate' command
  test/integration/Main.hs
Labels: merge me

#1225 Immediately flag world for redraw when scanning/uploading
  src/Swarm/Game/Step.hs
  src/Swarm/TUI/Controller.hs
Labels: merge me

#1216 More efficient gopher solution using 'watch'
  data/scenarios/Challenges/_gopher/solution.sw
  data/scenarios/Challenges/gopher.yaml
  test/integration/Main.hs
Labels: merge me, Z-Performance

#1214 Key input handler
  app/Main.hs
  data/entities.yaml
  data/recipes.yaml
  data/scenarios/Challenges/bridge-building.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  example/multi-key-handler.sw
  example/pilotmode.sw
  src/Swarm/Doc/Gen.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Key.hs
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/Language/Types.hs
  src/Swarm/Language/Value.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Repl.hs
  src/Swarm/TUI/View.hs
  swarm.cabal
  test/unit/TestCommand.hs
Labels: merge me

#1219 implement stride command
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1218-stride-command.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
Labels: merge me

#1142 web api to parse, render, and run code
  src/Swarm/App.hs
  src/Swarm/ReadableIORef.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/Web.hs
  swarm.cabal
Labels: merge me

#1226 mention `unit` and `void` types in `ADT calculator` description
  data/entities.yaml
Labels: merge me

#1233 Immersive multimedia experience
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Util.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Util.hs
Labels: merge me

#1231 unrestricted variant of atomic
  data/scenarios/Challenges/_word-search/create-puzzle.sw
  data/scenarios/Challenges/word-search.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
Labels: merge me

#1235 Implement push command
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1218-stride-command.yaml
  data/scenarios/Testing/1234-push-command.yaml
  data/scenarios/Testing/394-build-drill.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  test/integration/Main.hs
Labels: merge me

#1236 place hanoi files in subdirectory
  data/scenarios/Challenges/_hanoi/hanoi-count.sw
  data/scenarios/Challenges/_hanoi/hanoi-increasing.sw
  data/scenarios/Challenges/_hanoi/hanoi-invariant.sw
  data/scenarios/Challenges/_hanoi/hanoi-solution.sw
  data/scenarios/Challenges/hanoi.yaml
Labels: merge me
