Repository swarm-game/swarm, pull requests merged in 2023-01, with the labels that each got.

#911 Use custom types for immediate update
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Recipe.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/World.hs
Labels: merge me

#949 Nested sum type for directions
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Display.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Syntax.hs
Labels: Z-Refactoring, merge me

#948 Better CESK machine pretty-printing
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Step.hs
Labels: merge me

#952 extract display functions to new module
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/CellDisplay.hs
  swarm.cabal
Labels: merge me

#951 use more builtins from linear package
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Syntax.hs
Labels: merge me

#940 Fix hypothetical result of condition
  data/scenarios/Testing/858-inventory/858-nonpossession-objective.yaml
  src/Swarm/Game/Step.hs
  test/integration/Main.hs
Labels: merge me

#958 bump timeout for sporadic failures
  test/integration/Main.hs
Labels: merge me

#959 Fix capability checking, and refactor/add lots of comments
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/397-wrong-missing.yaml
  src/Swarm/Game/Step.hs
  test/integration/Main.hs
Labels: merge me

#962 Fix `EntityMap` merging
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/961-custom-capabilities.yaml
  src/Swarm/Game/Entity.hs
  test/integration/Main.hs
Labels: merge me

#956 Add `GPS receiver` device to provide `senseloc` capability
  data/entities.yaml
  data/recipes.yaml
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/956-GPS.yaml
  src/Swarm/Language/Capability.hs
  test/integration/Main.hs
Labels: merge me

#968 Add `isempty : cmd bool` to check whether current cell has an entity
  data/entities.yaml
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/958-isempty.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  test/integration/Main.hs
Labels: merge me

#975 Fix IDE by bumping stack LTS version to GHC 9.2:
  stack.yaml
Labels: merge me

#972 swarm-lang IDE hover
  src/Swarm/DocGen.hs
  src/Swarm/Language/LSP.hs
  src/Swarm/Language/LSP/Hover.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Util.hs
  swarm.cabal
Labels: merge me

#943 Create swarm subdirectories as necessary
  src/Swarm/TUI/Model/Achievement/Persistence.hs
  src/Swarm/Util.hs
Labels: merge me

#978 strip `VResult` before storing value in `REPLDone`
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Value.hs
  src/Swarm/TUI/Controller.hs
Labels: merge me

#908 Add the full expected location for the data directory
  src/Swarm/Util.hs
Labels: merge me

#982 Extend logs for warnings
  src/Swarm/App.hs
  src/Swarm/Game/Log.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Step.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Failure.hs
  src/Swarm/TUI/View.hs
  swarm.cabal
Labels: merge me

#954 One file per achievement record
  src/Swarm/TUI/Model/Achievement/Persistence.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
Labels: merge me

#992 shrink hover code
  src/Swarm/Language/LSP/Hover.hs
Labels: merge me

#993 Include `SrcLoc` info with variable binding sites
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
Labels: merge me

#989 The great `install`/`equip` switch
  data/entities.yaml
  data/recipes.yaml
  data/scenarios/Challenges/Ranching/_gated-paddock/enclosure-checking.sw
  data/scenarios/Challenges/Ranching/_gated-paddock/fence-construction.sw
  data/scenarios/Challenges/Ranching/gated-paddock.yaml
  data/scenarios/Challenges/_bucket-brigade/brigade.sw
  data/scenarios/README.md
  data/scenarios/Testing/201-require/201-require-device-creative.yaml
  data/scenarios/Testing/201-require/201-require-device-creative1.yaml
  data/scenarios/Testing/201-require/201-require-device.yaml
  data/scenarios/Testing/201-require/533-reprogram-simple.yaml
  data/scenarios/Testing/201-require/533-reprogram.yaml
  data/scenarios/Testing/961-custom-capabilities.yaml
  data/scenarios/Tutorials/00-ORDER.txt
  data/scenarios/Tutorials/README.md
  data/scenarios/Tutorials/equip.yaml
  data/scenarios/Tutorials/farming.yaml
  data/scenarios/Tutorials/require.yaml
  data/scenarios/Tutorials/requireinv.yaml
  data/scenarios/Tutorials/world101.yaml
  data/scenarios/classic.yaml
  data/schema/entities.json
  data/schema/robot.json
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/DocGen.hs
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Exception.hs
  src/Swarm/Game/Recipe.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/LSP/Hover.hs
  src/Swarm/Language/Requirement.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/TUI/View.hs
  test/integration/Main.hs
  test/unit/TestNotification.hs
Labels: merge me

#995 Isolate work directory for 'stack test'
  .gitignore
  CONTRIBUTING.md
  scripts/run-tests.sh
Labels: merge me

#999 word search
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_word-search/create-puzzle.sw
  data/scenarios/Challenges/_word-search/solution.sw
  data/scenarios/Challenges/_word-search/verify-solution.sw
  data/scenarios/Challenges/word-search.yaml
  test/integration/Main.hs
Labels: merge me

#1009 stack exec invocation script with --fast compilation
  scripts/play.sh
Labels: merge me

#1008 Ice Cream Shop
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_ice-cream/customer.sw
  data/scenarios/Challenges/_ice-cream/solution.sw
  data/scenarios/Challenges/ice-cream.yaml
  test/integration/Main.hs
Labels: merge me

#1004 Ensure unique solution for word search
  data/scenarios/Challenges/_word-search/create-puzzle.sw
  data/scenarios/Challenges/_word-search/verify-solution.sw
  data/scenarios/Challenges/word-search.yaml
Labels: merge me

#1018 swarm logo animation
  data/scenarios/Fun/00-ORDER.txt
  data/scenarios/Fun/_logo-burst/coordinator.sw
  data/scenarios/Fun/_logo-burst/drone.sw
  data/scenarios/Fun/logo-burst.yaml
Labels: merge me

#983 warn of unused variables
  data/test/language-snippets/warnings/unused-vars/multiple-lambda-first-unused.sw
  data/test/language-snippets/warnings/unused-vars/multiple-lambda-second-unused.sw
  data/test/language-snippets/warnings/unused-vars/multiple-let-all-unused.sw
  data/test/language-snippets/warnings/unused-vars/multiple-let-first-unused.sw
  data/test/language-snippets/warnings/unused-vars/multiple-let-second-unused.sw
  data/test/language-snippets/warnings/unused-vars/recursive-let.sw
  data/test/language-snippets/warnings/unused-vars/shadowed-variable-lambda-unused.sw
  data/test/language-snippets/warnings/unused-vars/shadowed-variable-let-intermediate-use.sw
  data/test/language-snippets/warnings/unused-vars/shadowed-variable-let-unused.sw
  data/test/language-snippets/warnings/unused-vars/single-bind-unused.sw
  data/test/language-snippets/warnings/unused-vars/single-bind-used.sw
  src/Swarm/Language/LSP.hs
  src/Swarm/Language/LSP/VarUsage.hs
  src/Swarm/Language/Syntax.hs
  swarm.cabal
  test/unit/Main.hs
  test/unit/TestLSP.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1023 support 'orientationMap'
  data/scenarios/README.md
  src/Swarm/Language/Syntax.hs
Labels: merge me

#1027 Device with recipe for 'appear' capability
  data/entities.yaml
  data/recipes.yaml
Labels: merge me

#514 Link TODOs to Issues
  .github/workflows/check_todos.yml
  src/Swarm/Game/Log.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/LSP.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/StateUpdate.hs
Labels: merge me, Z-Meta

#1022 Show duplicate robot logs
  data/scenarios/Tutorials/crash-secret.sw
  data/scenarios/Tutorials/farming.sw
  src/Swarm/Language/Syntax.hs
  src/Swarm/TUI/View.hs
  test/integration/Main.hs
Labels: merge me

#991 Annotate ASTs with types at every node
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Value.hs
  src/Swarm/Language/Elaborate.hs
  src/Swarm/Language/Module.hs
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Pipeline.hs
  src/Swarm/Language/Pipeline/QQ.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/Language/Types.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/Util.hs
  swarm.cabal
  test/integration/Main.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#927 Boolean expressions of objective prerequisites
  .gitignore
  data/scenarios/Challenges/Ranching/gated-paddock.yaml
  data/scenarios/Challenges/bucket-brigade.yaml
  data/scenarios/Challenges/word-search.yaml
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/378-objectives.yaml
  data/scenarios/Testing/795-prerequisite/00-ORDER.txt
  data/scenarios/Testing/795-prerequisite/795-prerequisite-and.yaml
  data/scenarios/Testing/795-prerequisite/795-prerequisite-cycle-with-not.yaml
  data/scenarios/Testing/795-prerequisite/795-prerequisite-mutually-exclusive.yaml
  data/scenarios/Testing/795-prerequisite/795-prerequisite-or.yaml
  data/scenarios/Testing/_Validation/795-prerequisite-cycle.yaml
  data/scenarios/Testing/_Validation/795-prerequisite-nonexistent-reference.yaml
  data/scenarios/Testing/_Validation/795-prerequisite-self-reference.yaml
  data/scenarios/Tutorials/bind2.yaml
  data/scenarios/Tutorials/farming.yaml
  data/scenarios/Tutorials/move.yaml
  data/scenarios/Tutorials/world101.yaml
  src/Data/BoolExpr.hs
  src/Data/BoolExpr/Simplify.hs
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Exception.hs
  src/Swarm/Game/Recipe.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Objective.hs
  src/Swarm/Game/Scenario/Objective/Graph.hs
  src/Swarm/Game/Scenario/Objective/Logic.hs
  src/Swarm/Game/Scenario/Objective/Presentation/Model.hs
  src/Swarm/Game/Scenario/Objective/Presentation/Render.hs
  src/Swarm/Game/Scenario/Objective/Validation.hs
  src/Swarm/Game/Scenario/Objective/WinCheck.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Value.hs
  src/Swarm/Language/Context.hs
  src/Swarm/TUI/Attr.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Achievement/Definitions.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/TUI/Model/Name.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Util.hs
  src/Swarm/Web.hs
  swarm.cabal
  test/integration/Main.hs
  test/unit/Main.hs
  test/unit/TestBoolExpr.hs
Labels: merge me

#1045 Todo enforcement line number
  .github/workflows/check_todos.yml
  scripts/enforce-todo-issues.sh
Labels: merge me

#1048 Move `Swarm.Game.Value` -> `Swarm.Language.Value`
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Value.hs
  src/Swarm/TUI/Controller.hs
  swarm.cabal
  test/unit/TestEval.hs
  test/unit/TestUtil.hs
Labels: merge me

#944 Wolf, Goat, Cabbage scenario
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_wolf-goat-cabbage/cross.sw
  data/scenarios/Challenges/_wolf-goat-cabbage/multi-item-possession.sw
  data/scenarios/Challenges/_wolf-goat-cabbage/together-on-east-bank.sw
  data/scenarios/Challenges/_wolf-goat-cabbage/unattended-together.sw
  data/scenarios/Challenges/wolf-goat-cabbage.yaml
Labels: merge me

#1053 Add some goals to speedrun scenarios
  data/scenarios/Speedruns/curry.yaml
  data/scenarios/Speedruns/forester.yaml
  data/scenarios/Speedruns/mithril.yaml
Labels: merge me

#945 Add achievement for losing
  src/Swarm/Game/Step.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Achievement/Attainment.hs
  src/Swarm/TUI/Model/Achievement/Definitions.hs
  src/Swarm/TUI/Model/Achievement/Description.hs
  src/Swarm/TUI/Model/StateUpdate.hs
Labels: merge me

#986 Improve OnHover for Def/Let, App and Const
  src/Swarm/Language/LSP/Hover.hs
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Syntax.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1056 Change `pickerelweed` to standard `flower` in `build` tutorial
  data/scenarios/Tutorials/build.yaml
Labels: merge me

#1055 Focus ring for goals modal
  src/Swarm/Game/Scenario/Objective/Presentation/Model.hs
  src/Swarm/Game/Scenario/Objective/Presentation/Render.hs
  src/Swarm/TUI/Attr.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Name.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Util.hs
Labels: merge me

#1058 support custom attributes defined in scenarios
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1034-custom-attributes.yaml
  src/Swarm/App.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Objective/Presentation/Render.hs
  src/Swarm/Game/Scenario/Style.hs
  src/Swarm/Game/State.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View/CustomStyling.hs
  swarm.cabal
Labels: merge me

#1001 Update to GHC 9.4 and `brick` 1.5
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/TUI/Model/Name.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Util.hs
  stack.yaml
  swarm.cabal
Labels: merge me

#1061 Add a changelog entry for 0.3.0.0 release
  CHANGELOG.md
  swarm.cabal
Labels: merge me

#1065 Fix scenarios being skipped or repeated when choosing "keep playing"
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Menu.hs
Labels: merge me

#1067 Tutorial improvements
  data/scenarios/Tutorials/bind2.yaml
  data/scenarios/Tutorials/require.yaml
Labels: merge me

#1071 also run `handleInfoPanelEvent` for dialogs other than `GoalModal`
  src/Swarm/TUI/Controller.hs
Labels: merge me

#1073 Check that base has a logger installed in tutorial
  data/scenarios/Tutorials/backstory.yaml
  test/integration/Main.hs
Labels: merge me
