Repository swarm-game/swarm, pull requests merged in 2023-02, with the labels that each got.

#1077 0.3.0.1 release
  CHANGELOG.md
  swarm.cabal
Labels: merge me

#1078 allow `vty-5.38`
  swarm.cabal
Labels: merge me

#1024 Make `sand` a bit harder to get
  data/entities.yaml
  data/recipes.yaml
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1024-sand.yaml
  test/integration/Main.hs
Labels: merge me

#1080 Fix goal dependence for Ice Cream Shop
  data/scenarios/Challenges/ice-cream.yaml
Labels: merge me, G-Scenarios

#1090 lower max bounds on yaml package
  swarm.cabal
Labels: merge me

#1085 Parse --run code instead of wrapping with run() command
  src/Swarm/Game/State.hs
  src/Swarm/Language/Pipeline.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  swarm.cabal
Labels: merge me

#1094 insert spacer between goal categories
  src/Swarm/Game/Scenario/Objective/Presentation/Model.hs
  src/Swarm/Game/Scenario/Objective/Presentation/Render.hs
  src/Swarm/TUI/Controller.hs
Labels: T-UI, merge me

#1100 Use internal attribute type in Display
  src/Swarm/Game/Display.hs
  src/Swarm/Game/Terrain.hs
  src/Swarm/TUI/Attr.hs
  src/Swarm/TUI/View/CellDisplay.hs
Labels: merge me

#1101 improve github action name
  .github/workflows/check_todos.yml
Labels: merge me

#1104 Make autoplay imply cheating
  src/Swarm/TUI/Model/StateUpdate.hs
Labels: merge me

#1103 Move Heading and conversions to Location module
  bench/Benchmark.hs
  src/Swarm/DocGen.hs
  src/Swarm/Game/Location.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Syntax.hs
Labels: merge me

#1109 Allow scrolling the world map unless `scrollable: false` is set
  data/scenarios/README.md
  data/scenarios/Tutorials/backstory.yaml
  data/scenarios/Tutorials/farming.yaml
  data/scenarios/Tutorials/world101.yaml
  data/scenarios/classic.yaml
  data/schema/world.json
  src/Swarm/Game/Scenario/WorldDescription.hs
  src/Swarm/Game/State.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/View.hs
Labels: merge me

#1114 allow `text-zipper-0.13` and `witch-1.2`
  swarm.cabal
Labels: merge me

#1117 Fix TODO action ID
  .github/workflows/check_todos.yml
Labels: merge me

#1118 Save time upon finishing scenario
  src/Swarm/Game/ScenarioInfo.hs
  src/Swarm/TUI/Controller.hs
Labels: merge me

#1081 Add tweezers for debugging
  data/entities.yaml
  data/recipes.yaml
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  test/unit/TestUtil.hs
Labels: merge me

#1116 Plumb rich failure types
  src/Swarm/DocGen.hs
  src/Swarm/Game/Achievement/Persistence.hs
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Failure.hs
  src/Swarm/Game/Failure/Render.hs
  src/Swarm/Game/Recipe.hs
  src/Swarm/Game/ResourceLoading.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/ScenarioInfo.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Failure.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/Util.hs
  swarm.cabal
Labels: merge me

#1133 fix yaml compilation error
  swarm.cabal
Labels: merge me
