Repository swarm-game/swarm, pull requests merged in 2023-05, with the labels that each got.

#974 Record best code size
  data/test/language-snippets/code-size/double-move-def-with-invocation.sw
  data/test/language-snippets/code-size/double-move-let-with-invocation.sw
  data/test/language-snippets/code-size/single-def-two-args-recursive-with-invocation.sw
  data/test/language-snippets/code-size/single-def-two-args-recursive.sw
  data/test/language-snippets/code-size/single-move-bare.sw
  data/test/language-snippets/code-size/single-move-def-with-invocation.sw
  data/test/language-snippets/code-size/single-move-def.sw
  data/test/language-snippets/code-size/single-move-let-with-invocation.sw
  src/Swarm/Game/Scenario/Scoring/Best.hs
  src/Swarm/Game/Scenario/Scoring/CodeSize.hs
  src/Swarm/Game/Scenario/Scoring/ConcreteMetrics.hs
  src/Swarm/Game/Scenario/Scoring/GenericMetrics.hs
  src/Swarm/Game/Scenario/Status.hs
  src/Swarm/Game/ScenarioInfo.hs
  src/Swarm/Game/State.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/TUI/Model/Repl.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/View.hs
  swarm.cabal
  test/unit/Main.hs
  test/unit/TestScoring.hs
Labels: merge me

#1241 finer texture for static
  src/Swarm/TUI/View/CellDisplay.hs
Labels: merge me

#1243 Fix scenario menu update after quitting to menu
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/StateUpdate.hs
Labels: Bug, merge me

#1244 reduce lag in monitor bot for Maypole scenario
  data/scenarios/Challenges/_maypole/monitor.sw
Labels: merge me

#1248 Do not show static when no robots exist in creative mode
  src/Swarm/TUI/View/CellDisplay.hs
Labels: merge me

#1249 add new `give` tutorial
  data/scenarios/Tutorials/00-ORDER.txt
  data/scenarios/Tutorials/give.yaml
  test/integration/Main.hs
Labels: merge me

#1250 Inventory search/filter mode
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Util.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  swarm.cabal
Labels: merge me

#1253 Display higher clock resolution at lower speeds
  src/Swarm/TUI/View.hs
  src/Swarm/Util.hs
Labels: merge me

#1255 CLI option to set initial speed
  app/Main.hs
  src/Swarm/App.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
Labels: merge me

#1252 Better type variable names
  src/Swarm/Language/Typecheck.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1076 Make panes collapsible
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
Labels: merge me

#1261 decouple relative and absolute time capabilities
  data/entities.yaml
  src/Swarm/Language/Capability.hs
Labels: merge me

#1263 canonical devices for push, watch, sniff
  data/entities.yaml
  data/scenarios/Challenges/gopher.yaml
  data/scenarios/Testing/1234-push-command.yaml
Labels: merge me

#1258 Pig capturing scenario
  data/scenarios/Challenges/Ranching/00-ORDER.txt
  data/scenarios/Challenges/Ranching/_capture/design-commentary.md
  data/scenarios/Challenges/Ranching/_capture/opponent.sw
  data/scenarios/Challenges/Ranching/_capture/solution.sw
  data/scenarios/Challenges/Ranching/capture.yaml
  src/Swarm/TUI/Controller.hs
  test/integration/Main.hs
Labels: merge me

#1269 sokoban levels
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/Sokoban/00-ORDER.txt
  data/scenarios/Challenges/Sokoban/Gadgets/00-ORDER.txt
  data/scenarios/Challenges/Sokoban/Gadgets/README.md
  data/scenarios/Challenges/Sokoban/Gadgets/no-reverse.yaml
  data/scenarios/Challenges/Sokoban/Gadgets/one-way.yaml
  data/scenarios/Challenges/Sokoban/Simple/00-ORDER.txt
  data/scenarios/Challenges/Sokoban/Simple/trapdoor.yaml
  data/scenarios/Challenges/Sokoban/_foresight/solution.sw
  data/scenarios/Challenges/Sokoban/foresight.yaml
  data/scenarios/Testing/1234-push-command.yaml
  test/integration/Main.hs
Labels: merge me

#1272 Allow zero-tick recipes to apply immediately
  src/Swarm/Game/Step.hs
Labels: merge me

#1275 use isPrivilegedBot more
  src/Swarm/Game/Step.hs
  src/Swarm/Game/World.hs
Labels: Z-Refactoring, merge me

#1273 lights out
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_lights-out/assistant.sw
  data/scenarios/Challenges/_lights-out/design-commentary.md
  data/scenarios/Challenges/_lights-out/solution.sw
  data/scenarios/Challenges/lights-out.yaml
  test/integration/Main.hs
Labels: merge me

#1277 Recreate `GameState` from scratch when starting a scenario
  bench/Benchmark.hs
  src/Swarm/App.hs
  src/Swarm/Game/State.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  test/integration/Main.hs
  test/unit/Main.hs
  test/unit/TestPedagogy.hs
Labels: merge me

#1283 Rework type checker using "propagate types inward" trick
  src/Swarm/Language/Pipeline.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/Language/Typecheck/Unify.hs
  swarm.cabal
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1288 Extract drilling logic
  src/Swarm/Game/Step.hs
Labels: Z-Refactoring, merge me
