Repository swarm-game/swarm, pull requests merged in 2023-07, with the labels that each got.

#1358 planar direction sum type
  editors/emacs/swarm-mode.el
  editors/vscode/DEVELOPING.md
  editors/vscode/package-lock.json
  editors/vscode/syntaxes/swarm.tmLanguage.json
  editors/vscode/test/hello.sw.snap
  src/Swarm/Game/Location.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Syntax.hs
Labels: Z-Refactoring, merge me

#1359 better JSON direction representation
  data/scenarios/Testing/1138-structures/flip-and-rotate.yaml
  data/scenarios/Vignettes/roadway.yaml
  src/Swarm/Language/Syntax.hs
Labels: merge me, Z-Developer Experience

#1356 waypoints and portals
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1356-portals/00-ORDER.txt
  data/scenarios/Testing/1356-portals/_automatic-waypoint-patrol/program.sw
  data/scenarios/Testing/1356-portals/_portals-flip-and-rotate/solution.sw
  data/scenarios/Testing/1356-portals/automatic-waypoint-patrol.yaml
  data/scenarios/Testing/1356-portals/portals-and-waypoints.yaml
  data/scenarios/Testing/1356-portals/portals-flip-and-rotate.yaml
  data/scenarios/Testing/_Validation/1356-ambiguous-portal-entrance.yaml
  data/scenarios/Testing/_Validation/1356-ambiguous-portal-exit.yaml
  data/scenarios/Testing/_Validation/1356-waypoint-uniqueness-enforcement.yaml
  editors/emacs/swarm-mode.el
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Topography/Area.hs
  src/Swarm/Game/Scenario/Topography/Cell.hs
  src/Swarm/Game/Scenario/Topography/EntityFacade.hs
  src/Swarm/Game/Scenario/Topography/Navigation/Portal.hs
  src/Swarm/Game/Scenario/Topography/Navigation/Waypoint.hs
  src/Swarm/Game/Scenario/Topography/Placement.hs
  src/Swarm/Game/Scenario/Topography/Structure.hs
  src/Swarm/Game/Scenario/Topography/WorldDescription.hs
  src/Swarm/Game/Scenario/Topography/WorldPalette.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Value.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/TUI/Editor/Controller.hs
  src/Swarm/TUI/Editor/Json.hs
  src/Swarm/TUI/Editor/Model.hs
  src/Swarm/TUI/Editor/Palette.hs
  src/Swarm/TUI/Editor/Util.hs
  src/Swarm/TUI/Editor/View.hs
  src/Swarm/TUI/View/CellDisplay.hs
  src/Swarm/Util.hs
  src/Swarm/Util/Yaml.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#1326 Fourmolu fixup
  .restyled.yaml
  CONTRIBUTING.md
  fourmolu.yaml
  scripts/reformat-code.sh
  src/Swarm/Game/Scenario/Topography/Cell.hs
  src/Swarm/Game/Scenario/Topography/Structure.hs
  src/Swarm/TUI/View/CellDisplay.hs
Labels: merge me

#1378 Use robotMap directly instead of addRobot
  src/Swarm/Game/Step.hs
Labels: merge me

#1375 Change binding on Hide REPL to M-,
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/View.hs
Labels: merge me

#1383 Load persistent state from disk only once and reuse for all integration tests
  src/Swarm/TUI/Model/StateUpdate.hs
  test/integration/Main.hs
Labels: merge me

#1384 Update about to 2023
  data/about.txt
Labels: merge me

#1386 Highlight ticks per frame in red when it reaches the cap
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/View.hs
Labels: merge me

#1353 subworlds
  bench/Benchmark.hs
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/144-subworlds/00-ORDER.txt
  data/scenarios/Testing/144-subworlds/_basic-subworld/solution.sw
  data/scenarios/Testing/144-subworlds/_subworld-located-robots/solution.sw
  data/scenarios/Testing/144-subworlds/_subworld-mapped-robots/judges.sw
  data/scenarios/Testing/144-subworlds/_subworld-mapped-robots/solution.sw
  data/scenarios/Testing/144-subworlds/basic-subworld.yaml
  data/scenarios/Testing/144-subworlds/spatial-consistency-enforcement.yaml
  data/scenarios/Testing/144-subworlds/subworld-located-robots.yaml
  data/scenarios/Testing/144-subworlds/subworld-mapped-robots.yaml
  data/scenarios/Testing/144-subworlds/subworld-shared-structures.yaml
  data/scenarios/Testing/_Validation/144-spatial-consistency-enforcement.yaml
  data/scenarios/Testing/_Validation/144-subworld-uniqueness-enforcement-default.yaml
  data/scenarios/Testing/_Validation/144-subworld-uniqueness-enforcement-named.yaml
  scripts/enforce-todo-issues.sh
  src/Swarm/Doc/Gen.hs
  src/Swarm/Game/Log.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/RobotLookup.hs
  src/Swarm/Game/Scenario/Topography/Cell.hs
  src/Swarm/Game/Scenario/Topography/Navigation/Portal.hs
  src/Swarm/Game/Scenario/Topography/Structure.hs
  src/Swarm/Game/Scenario/Topography/WorldDescription.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Universe.hs
  src/Swarm/Game/World.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Util.hs
  src/Swarm/TUI/Editor/Controller.hs
  src/Swarm/TUI/Editor/Masking.hs
  src/Swarm/TUI/Editor/Model.hs
  src/Swarm/TUI/Editor/Palette.hs
  src/Swarm/TUI/Editor/Util.hs
  src/Swarm/TUI/Editor/View.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/Name.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/CellDisplay.hs
  src/Swarm/Util.hs
  src/Swarm/Version.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#1390 Automatic re-orientation via portal
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1379-single-world-portal-reorientation.yaml
  data/scenarios/Testing/144-subworlds/spatial-consistency-enforcement.yaml
  src/Swarm/Game/Scenario/Topography/Navigation/Portal.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Direction.hs
  src/Swarm/Language/Syntax.hs
  swarm.cabal
  test/integration/Main.hs
Labels: Z-Refactoring, merge me, L-Commands, G-Scenarios

#1391 Continue parsing the rest of the scenarios in a directory when one fails
  src/Swarm/Game/ScenarioInfo.hs
Labels: merge me
