Repository swarm-game/swarm, pull requests merged in 2023-09, with the labels that each got.

#1481 Improvements to scrolling
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/Name.hs
  src/Swarm/TUI/Model/Repl.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  stack.yaml
  swarm.cabal
Labels: merge me, CHANGELOG

#1487 Print REPL errors inline and get rid of error popup
  data/scenarios/Tutorials/type-errors.yaml
  data/scenarios/Tutorials/types.yaml
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Repl.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
Labels: merge me, CHANGELOG

#1488 Some documentation improvements + refactoring
  src/Swarm/App.hs
  src/Swarm/Constant.hs
  src/Swarm/Doc/Gen.hs
  src/Swarm/Doc/Pedagogy.hs
  src/Swarm/Game/Achievement/Attainment.hs
  src/Swarm/Game/Achievement/Definitions.hs
  src/Swarm/Game/Achievement/Description.hs
  src/Swarm/Game/Achievement/Persistence.hs
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Entity.hs
  src/Swarm/Game/Exception.hs
  src/Swarm/Game/Failure.hs
  src/Swarm/Game/Location.hs
  src/Swarm/Game/Recipe.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/World.hs
  src/Swarm/TUI/View.hs
Labels: merge me

#1484 Robot activity counts in F2 menu
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1341-command-count.yaml
  src/Swarm/Game/CESK.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/TUI/Editor/View.hs
  src/Swarm/TUI/Launch/View.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Achievement.hs
  src/Swarm/TUI/View/Attribute/Attr.hs
  src/Swarm/TUI/View/Attribute/CustomStyling.hs
  src/Swarm/TUI/View/Attribute/Util.hs
  src/Swarm/TUI/View/CellDisplay.hs
  src/Swarm/TUI/View/Objective.hs
  src/Swarm/TUI/View/Util.hs
  src/Swarm/Util/UnitInterval.hs
  src/Swarm/Util/WindowedCounter.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me, CHANGELOG

#1493 more documentation tweaks
  scripts/view-haddocks.sh
  src/Swarm/Game/Recipe.hs
  src/Swarm/Game/ResourceLoading.hs
  src/Swarm/Game/Step/Util.hs
  src/Swarm/TUI/Model/Goal.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#1497 Use raw (unelaborated) AST for pretty-printing in Markdown
  src/Swarm/Language/Text/Markdown.hs
Labels: merge me, CHANGELOG

#1498 Add solution for world101 tutorial
  data/scenarios/Tutorials/world101.sw
  data/scenarios/Tutorials/world101.yaml
  test/integration/Main.hs
Labels: merge me

#1500 add more markup to scenario descriptions
  data/scenarios/Challenges/2048.yaml
  data/scenarios/Challenges/Mazes/easy_cave_maze.yaml
  data/scenarios/Challenges/Ranching/capture.yaml
  data/scenarios/Challenges/Ranching/gated-paddock.yaml
  data/scenarios/Challenges/Ranching/powerset.yaml
  data/scenarios/Challenges/Sliding Puzzles/3x3.yaml
  data/scenarios/Challenges/Sokoban/Gadgets/no-reverse.yaml
  data/scenarios/Challenges/Sokoban/Gadgets/one-way.yaml
  data/scenarios/Challenges/Sokoban/Simple/trapdoor.yaml
  data/scenarios/Challenges/Sokoban/foresight.yaml
  data/scenarios/Challenges/arbitrage.yaml
  data/scenarios/Challenges/blender.yaml
  data/scenarios/Challenges/bridge-building.yaml
  data/scenarios/Challenges/bucket-brigade.yaml
  data/scenarios/Challenges/chess_horse.yaml
  data/scenarios/Challenges/gopher.yaml
  data/scenarios/Challenges/hackman.yaml
  data/scenarios/Challenges/ice-cream.yaml
  data/scenarios/Challenges/maypole.yaml
  data/scenarios/Challenges/teleport.yaml
  data/scenarios/Challenges/wolf-goat-cabbage.yaml
  data/scenarios/Challenges/word-search.yaml
  data/scenarios/Speedruns/curry.yaml
  data/scenarios/Speedruns/forester.yaml
  data/scenarios/Speedruns/mithril.yaml
  data/scenarios/Tutorials/world101.yaml
Labels: merge me

#1499 Use NonEmpty to eliminate some partial functions
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Attribute/Attr.hs
Labels: merge me

#1501 generalize variables bound by `<-`
  src/Swarm/Language/Typecheck.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1505 Fix build error regarding 'tasty' bounds
  swarm.cabal
Labels: merge me

#1508 Support markdown in achievement descriptions
  src/Swarm/Game/Achievement/Definitions.hs
  src/Swarm/Game/Achievement/Description.hs
  src/Swarm/TUI/View/Achievement.hs
Labels: merge me

#1509 Add footer to goals dialog
  src/Swarm/TUI/View/Objective.hs
Labels: T-UI, merge me

#1503 Replace/quarantine uses of `head` and `NE.fromList` functions
  .hlint.yaml
  src/Swarm/Doc/Gen.hs
  src/Swarm/Game/Exception.hs
  src/Swarm/Game/Failure.hs
  src/Swarm/Game/Scenario/Topography/Cell.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Terrain.hs
  src/Swarm/Game/World/Parse.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/Util.hs
Labels: Z-Refactoring, merge me, Z-Developer Experience

#1504 Grant `RobotIntoWater` achievement
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/Achievements/00-ORDER.txt
  data/scenarios/Testing/Achievements/RobotIntoWater.yaml
  src/Swarm/Game/Step.hs
  test/integration/Main.hs
Labels: merge me, CHANGELOG

#1510 Decompose GameState into sub-records
  bench/Benchmark.hs
  scripts/reformat-code.sh
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Step/Combustion.hs
  src/Swarm/Game/Step/Util.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Util.hs
  src/Swarm/TUI/Editor/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/CellDisplay.hs
  test/integration/Main.hs
  test/unit/TestNotification.hs
  test/unit/TestUtil.hs
Labels: Z-Refactoring, merge me

#1521 render scenario description as markdown
  src/Swarm/Doc/Pedagogy.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/TUI/Editor/Json.hs
  src/Swarm/TUI/Editor/Palette.hs
  src/Swarm/TUI/View.hs
Labels: T-UI, merge me

#1518 Add syntax highlighting and LSP configuration for Vim/Neovim
  editors/README.md
  editors/vim/swarm.lua
  editors/vim/swarm.vim
  src/Swarm/Doc/Gen.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#1522 Lengthen timeout for `Challenges/ice-cream`
  test/integration/Main.hs
Labels: merge me

#1513 Refactor `LogEntry` type
  scripts/run-tests.sh
  src/Swarm/App.hs
  src/Swarm/Game/Log.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/Log.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Attribute/Attr.hs
  swarm.cabal
  test/integration/Main.hs
  test/unit/TestNotification.hs
Labels: Z-Refactoring, merge me

#1515 Render map preview on scenario selection screen
  app/Main.hs
  src/Swarm/Doc/Gen.hs
  src/Swarm/Game/ResourceLoading.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Scenario.hs
  src/Swarm/Game/Scenario/Status.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step/Util.hs
  src/Swarm/Game/World/Render.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Util.hs
  src/Swarm/TUI/Editor/Controller.hs
  src/Swarm/TUI/Editor/Model.hs
  src/Swarm/TUI/Editor/Util.hs
  src/Swarm/TUI/Editor/View.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/CellDisplay.hs
  swarm.cabal
Labels: merge me

#1525 allow `megaparsec-9.5`
  swarm.cabal
Labels: merge me

#1527 Update Web module haddock
  src/Swarm/Web.hs
Labels: merge me

#1531 disambiguate doc links, elaborate waypoint ordering
  src/Swarm/Doc/Gen.hs
  src/Swarm/Game/Exception.hs
  src/Swarm/Game/Location.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Scenario/Style.hs
  src/Swarm/Game/Scenario/Topography/Area.hs
  src/Swarm/Game/Scenario/Topography/Navigation/Portal.hs
  src/Swarm/Game/Scenario/Topography/Navigation/Waypoint.hs
  src/Swarm/Game/Scenario/Topography/Structure.hs
  src/Swarm/Game/ScenarioInfo.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Step/Combustion.hs
  src/Swarm/Game/Universe.hs
  src/Swarm/Game/World/Coords.hs
  src/Swarm/Game/World/Typecheck.hs
  src/Swarm/Language/Direction.hs
  src/Swarm/Language/Key.hs
  src/Swarm/Language/Parse.hs
  src/Swarm/Language/Requirement.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Text/Markdown.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Launch/Prep.hs
  src/Swarm/TUI/Model/Repl.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
Labels: Z-Documentation, merge me

#1523 Pathfinding command
  bench/Benchmark.hs
  data/scenarios/Challenges/Ranching/_gated-paddock/enclosure-checking.sw
  data/scenarios/Challenges/Ranching/_gated-paddock/meandering-sheep.sw
  data/scenarios/Challenges/Ranching/_gated-paddock/update-and-test.sh
  data/scenarios/Challenges/Ranching/gated-paddock.yaml
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1536-custom-unwalkable-entities.yaml
  data/scenarios/Testing/836-pathfinding/00-ORDER.txt
  data/scenarios/Testing/836-pathfinding/836-automatic-waypoint-navigation.yaml
  data/scenarios/Testing/836-pathfinding/836-no-path-exists1.yaml
  data/scenarios/Testing/836-pathfinding/836-no-path-exists2.yaml
  data/scenarios/Testing/836-pathfinding/836-path-exists-distance-limit-reachable.yaml
  data/scenarios/Testing/836-pathfinding/836-path-exists-distance-limit-unreachable.yaml
  data/scenarios/Testing/836-pathfinding/836-path-exists-find-entity-unwalkable.yaml
  data/scenarios/Testing/836-pathfinding/836-path-exists-find-entity.yaml
  data/scenarios/Testing/836-pathfinding/836-path-exists-find-location.yaml
  data/scenarios/Testing/836-pathfinding/_836-automatic-waypoint-navigation/gardener.sw
  data/scenarios/Testing/836-pathfinding/_836-automatic-waypoint-navigation/patrol.sw
  data/scenarios/Testing/836-pathfinding/_836-automatic-waypoint-navigation/rabbit.sw
  data/scenarios/Testing/836-pathfinding/_836-path-exists/find-entity-solution.sw
  data/scenarios/Testing/836-pathfinding/_836-path-exists/find-entity-unwalkable-solution.sw
  data/scenarios/Testing/836-pathfinding/_836-path-exists/find-location-solution.sw
  data/schema/robot.json
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Step/Combustion.hs
  src/Swarm/Game/Step/Pathfinding.hs
  src/Swarm/Game/Step/Util.hs
  src/Swarm/Game/Value.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  src/Swarm/TUI/Editor/Controller.hs
  src/Swarm/Util.hs
  stack.yaml
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#1512 update CONTRIBUTING guide, and remove info from README
  CONTRIBUTING.md
  README.md
Labels: merge me

#1541 ping command
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1535-ping/00-ORDER.txt
  data/scenarios/Testing/1535-ping/1535-in-range.yaml
  data/scenarios/Testing/1535-ping/1535-out-of-range.yaml
  data/scenarios/Testing/1535-ping/_1535-in-range/buddy.sw
  data/scenarios/Testing/1535-ping/_1535-in-range/solution.sw
  data/scenarios/Testing/1535-ping/_1535-out-of-range/solution.sw
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/Swarm/Game/Location.hs
  src/Swarm/Game/Scenario/Topography/Navigation/Util.hs
  src/Swarm/Game/State.hs
  src/Swarm/Game/Step.hs
  src/Swarm/Game/Universe.hs
  src/Swarm/Language/Capability.hs
  src/Swarm/Language/Syntax.hs
  src/Swarm/Language/Typecheck.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#1549 Fix reference to nonexistent `entity` type
  src/Swarm/Language/Typecheck.hs
Labels: merge me

#1529 Web API docs improvements
  app/Main.hs
  src/Swarm/Doc/Gen.hs
  src/Swarm/Game/Robot.hs
  src/Swarm/Game/State.hs
  src/Swarm/Language/Pretty.hs
  src/Swarm/Language/Text/Markdown.hs
  src/Swarm/TUI/Model/Goal.hs
  src/Swarm/TUI/Model/Repl.hs
  src/Swarm/Web.hs
Labels: merge me
