Repository swarm-game/swarm, pull requests merged in 2024-10, with the labels that each got.

#2166 Add github action for Restyled
  .github/workflows/restyled.yml
Labels: merge me, Z-Developer Experience

#2164 better support for structure references
  data/scenarios/Testing/1138-structures/nested-structure.yaml
  data/scenarios/Testing/_Validation/2164-recursive-structure.yaml
  data/schema/named-structure.json
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/Scenario/Objective/Graph.hs
  src/swarm-scenario/Swarm/Game/Scenario/Objective/Validation.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition.hs
  src/swarm-util/Swarm/Util/Graph.hs
  swarm.cabal
Labels: T-Testing, merge me

#2172 Improve type inference for record projection
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-lang/Swarm/Language/Types.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#2170 Fix TyDef narrowToPosition
  src/swarm-lang/Swarm/Language/LSP/Hover.hs
Labels: merge me, CHANGELOG

#2175 Legend for colorization in F1 dialog
  src/swarm-tui/Swarm/TUI/View.hs
Labels: merge me

#1031 DNA copying challenge
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_dna/lab.sw
  data/scenarios/Challenges/_dna/mirrorbot.sw
  data/scenarios/Challenges/_dna/resetter.sw
  data/scenarios/Challenges/_dna/solution.sw
  data/scenarios/Challenges/_dna/topchecker.sw
  data/scenarios/Challenges/dna.yaml
  test/integration/Main.hs
Labels: merge me, G-Scenarios

#2180 use applyWhen
  src/swarm-doc/Swarm/Doc/Wiki/Cheatsheet.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-lang/Swarm/Language/LSP/Hover.hs
  src/swarm-lang/Swarm/Language/Requirements/Analysis.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Placement.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Editor/View.hs
  src/swarm-tui/Swarm/TUI/Launch/View.hs
  src/swarm-tui/Swarm/TUI/Model/Dialog/Goal.hs
  src/swarm-tui/Swarm/TUI/Model/Repl.hs
  src/swarm-tui/Swarm/TUI/Panel.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/CellDisplay.hs
  src/swarm-tui/Swarm/TUI/View/Robot.hs
  src/swarm-tui/Swarm/TUI/View/Robot/Details.hs
  src/swarm-util/Data/BoolExpr/Simplify.hs
  test/integration/Main.hs
  test/integration/TestRecipeCoverage.hs
Labels: Z-Refactoring, merge me

#2161 Dictionary example
  example/recursive-containers.sw
Labels: merge me

#2181 Fix autopause on complete game
  src/swarm-engine/Swarm/Game/Step.hs
Labels: merge me

#2184 render map preview as dynamic PNG
  app/scene/Main.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
  src/swarm-tournament/Swarm/Web/Tournament.hs
  swarm.cabal
  tournament/web/list-solutions.html
  tournament/web/script/list-solutions.js
Labels: merge me, T-Web

#2185 expose waypoint and portal info to web API
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Navigation/Portal.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Navigation/Waypoint.hs
  src/swarm-topography/Swarm/Game/Universe.hs
  src/swarm-web/Swarm/Web.hs
Labels: merge me, T-Web, Z-Developer Experience

#2187 Fix type inference for recursive let bindings
  src/swarm-lang/Swarm/Language/Typecheck.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#2178 Scoped type variables
  src/swarm-doc/Swarm/Doc/Command.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-lang/Swarm/Language/Context.hs
  src/swarm-lang/Swarm/Language/Elaborate.hs
  src/swarm-lang/Swarm/Language/Kindcheck.hs
  src/swarm-lang/Swarm/Language/LSP/Hover.hs
  src/swarm-lang/Swarm/Language/LSP/VarUsage.hs
  src/swarm-lang/Swarm/Language/Parser/Term.hs
  src/swarm-lang/Swarm/Language/Parser/Type.hs
  src/swarm-lang/Swarm/Language/Pipeline.hs
  src/swarm-lang/Swarm/Language/Requirements/Analysis.hs
  src/swarm-lang/Swarm/Language/Syntax/AST.hs
  src/swarm-lang/Swarm/Language/Syntax/Pattern.hs
  src/swarm-lang/Swarm/Language/Syntax/Pretty.hs
  src/swarm-lang/Swarm/Language/Syntax/Util.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-lang/Swarm/Language/Types.hs
  src/swarm-lang/Swarm/Language/Value.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  test/unit/TestLanguagePipeline.hs
  test/unit/TestPretty.hs
Labels: merge me

#2190 Add a progress bar vignette
  data/scenarios/Vignettes/00-ORDER.txt
  data/scenarios/Vignettes/progress-bar.yaml
Labels: merge me

#2195 subworld-aware teleportation and location query commands
  data/scenarios/Testing/144-subworlds/00-ORDER.txt
  data/scenarios/Testing/144-subworlds/teleport-and-query.yaml
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  editors/vscode/syntaxes/swarm.tmLanguage.yaml
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Value.hs
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  test/integration/Main.hs
Labels: merge me

#2165 bump containers version
  swarm.cabal
Labels: Z-Refactoring, merge me

#2199 Correct cycle finding for graphs
  data/scenarios/Testing/_Validation/2198-prerequisite-SCC.yaml
  src/swarm-util/Swarm/Util/Graph.hs
Labels: merge me
