Repository swarm-game/swarm, pull requests merged in 2024-07, with the labels that each got.

#2003 Use 'enumerate' from the 'extra' package
  .hlint.yaml
  src/swarm-doc/Swarm/Doc/Command.hs
  src/swarm-doc/Swarm/Doc/Gen.hs
  src/swarm-doc/Swarm/Doc/Wiki/Cheatsheet.hs
  src/swarm-engine/Swarm/Game/Step/Util/Inspect.hs
  src/swarm-lang/Swarm/Language/Parser/Lex.hs
  src/swarm-lang/Swarm/Language/Parser/Type.hs
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
  src/swarm-scenario/Swarm/Game/Achievement/Definitions.hs
  src/swarm-topography/Swarm/Game/Location.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Editor/Model.hs
  src/swarm-tui/Swarm/TUI/Launch/Controller.hs
  src/swarm-tui/Swarm/TUI/Launch/Prep.hs
  src/swarm-tui/Swarm/TUI/Model/Goal.hs
  src/swarm-tui/Swarm/TUI/Model/Menu.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/Model/Structure.hs
  src/swarm-tui/Swarm/TUI/Model/UI.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-util/Swarm/Language/Syntax/Direction.hs
  src/swarm-util/Swarm/Util.hs
Labels: Z-Refactoring, merge me

#1933 nonempty grid rows
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldPalette.hs
  src/swarm-scenario/Swarm/Game/State/Landscape.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
  src/swarm-scenario/Swarm/Util/Content.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Area.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Grid.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Placement.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Rasterize.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Overlay.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Symmetry.hs
  src/swarm-tui/Swarm/TUI/Editor/Controller.hs
  src/swarm-tui/Swarm/TUI/Editor/Palette.hs
  src/swarm-tui/Swarm/TUI/Editor/Util.hs
  src/swarm-tui/Swarm/TUI/View/Structure.hs
  src/swarm-web/Swarm/Web/Worldview.hs
  swarm.cabal
  test/unit/TestOverlay.hs
Labels: Z-Refactoring, merge me

#2005 Focus REPL panel on click
  src/swarm-tui/Swarm/TUI/Controller.hs
Labels: merge me

#2008 On C-c, only cancel base CESK if it is currently running
  src/swarm-tui/Swarm/TUI/Controller.hs
Labels: merge me

#2011 Update spelling dictionary
  .gitignore
  cspell.json
  scripts/gen/autopopulate-spellchecker.sh
  scripts/gen/hiedb.sh
Labels: merge me

#2012 Remove let-binding workarounds
  data/scenarios/Challenges/Ranching/_capture/opponent.sw
  data/scenarios/Challenges/Ranching/_powerset/setup.sw
  data/scenarios/Challenges/Sliding Puzzles/_sliding-puzzle/maintainer.sw
  data/scenarios/Challenges/_gallery/setup.sw
  data/scenarios/Challenges/_lights-out/assistant.sw
Labels: merge me

#1979 Customizable keybindings
  app/Main.hs
  src/swarm-engine/Swarm/Game/Achievement/Persistence.hs
  src/swarm-scenario/Swarm/Constant.hs
  src/swarm-scenario/Swarm/Game/Failure.hs
  src/swarm-scenario/Swarm/Game/ResourceLoading.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Frame.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Main.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/REPL.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Robot.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/World.hs
  src/swarm-tui/Swarm/TUI/Controller/SaveScenario.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/Model.hs
  src/swarm-tui/Swarm/TUI/Model/Achievements.hs
  src/swarm-tui/Swarm/TUI/Model/Event.hs
  src/swarm-tui/Swarm/TUI/Model/KeyBindings.hs
  src/swarm-tui/Swarm/TUI/Model/Menu.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/Util.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me, CHANGELOG

#2017 Replace minBound to maxBound with enumerate
  src/swarm-scenario/Swarm/Game/World/Parse.hs
  src/swarm-scenario/Swarm/Game/World/Typecheck.hs
Labels: merge me

#2025 Add recipe for hourglass
  data/recipes.yaml
Labels: merge me

#2000 Save current REPL input with down arrow
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/REPL.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/Model/Repl.hs
  src/swarm-tui/Swarm/TUI/Model/UI.hs
  src/swarm-tui/Swarm/TUI/View.hs
  test/unit/TestRepl.hs
Labels: merge me

#2029 update references from IRC -> Discord
  CODE_OF_CONDUCT.md
  COMMUNITY.md
  CONTRIBUTING.md
  data/about.txt
  src/swarm-scenario/Swarm/Constant.hs
  src/swarm-tui/Swarm/TUI/View.hs
Labels: merge me

#2031 Fix keybindings initialisation when directory is missing
  app/Main.hs
  src/swarm-scenario/Swarm/Game/ResourceLoading.hs
  src/swarm-tui/Swarm/TUI/Model/KeyBindings.hs
Labels: merge me

#2028 Rolex, Olfactometer, and Dozer Blade Recipes
  data/recipes.yaml
Labels: merge me

#2030 Recipe coverage graph test
  src/swarm-doc/Swarm/Doc/Gen.hs
  swarm.cabal
  test/integration/Main.hs
  test/integration/TestRecipeCoverage.hs
  test/unit/Main.hs
  test/unit/TestRecipeCoverage.hs
Labels: merge me

#2021 move more recognizer logic into topography sublibrary
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Prep.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#2035 extract state initialization to new module
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Initialize.hs
  src/swarm-tournament/Swarm/Web/Tournament/Validate.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  swarm.cabal
  test/bench/Benchmark.hs
Labels: Z-Refactoring, merge me

#2033 Filter recipe graph
  app/doc/Main.hs
  src/swarm-doc/Swarm/Doc/Gen.hs
Labels: merge me

#2027 Notification popups
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Initialize.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Frame.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/Model/Achievements.hs
  src/swarm-tui/Swarm/TUI/Model/Popup.hs
  src/swarm-tui/Swarm/TUI/Model/UI.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/Achievement.hs
  src/swarm-tui/Swarm/TUI/View/Popup.hs
  src/swarm-tui/Swarm/TUI/View/Util.hs
  swarm.cabal
Labels: merge me, CHANGELOG

#2039 Update GitHub release action
  .github/workflows/haskell-release.yml
Labels: merge me

#2037 Move top-level Github/VSCode configuration files
  .github/.mergify.yml
  .github/.restyled.yaml
  .github/pull_request_template.md
  .github/workflows/cabal.haskell-ci
  .github/workflows/haskell-ci.yml
  .gitignore
  .vscode/cspell.json
  scripts/gen/autopopulate-spellchecker.sh
Labels: merge me

#2042 Fix restyled & mergify
  .github/mergify.yml
  .github/restyled.yaml
Labels: merge me

#2034 simplify recognizer more
  src/swarm-engine/Swarm/Game/Scenario/Topography/Structure/Recognition/Tracking.hs
  src/swarm-engine/Swarm/Game/State/Initialize.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Log.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Prep.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Registry.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Symmetry.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Type.hs
  src/swarm-tui/Swarm/TUI/Model/Structure.hs
  src/swarm-tui/Swarm/TUI/View/Structure.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#2041 Pretty print readable unicode characters
  src/swarm-lang/Swarm/Language/Pretty.hs
  swarm.cabal
  test/unit/TestEval.hs
Labels: merge me

#2047 Fix the cheat sheet options
  app/doc/Main.hs
  src/swarm-doc/Swarm/Doc/Gen.hs
  src/swarm-doc/Swarm/Doc/Wiki/Cheatsheet.hs
Labels: merge me

#1980 0.6 release
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  swarm.cabal
Labels: merge me

#2051 Fix release URL asset path in Haskell release action
  .github/workflows/haskell-release.yml
Labels: merge me

#2052 set required cabal-version to 3.6
  swarm.cabal
Labels: merge me

#2049 Make logging intangible
  data/scenarios/Testing/475-wait-one.yaml
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
Labels: merge me

#2054 fix local server test scripts
  tournament/scripts/demo/client/fetch.sh
  tournament/scripts/demo/client/login.sh
  tournament/scripts/demo/client/submit.sh
Labels: T-Testing, merge me, T-Web

#2044 use weeder
  .github/workflows/haskell-ci.yml
  app/game/Main.hs
  app/game/Swarm/App.hs
  scripts/validate/weeder.sh
  src/swarm-engine/Swarm/Game/Scenario/Status.hs
  src/swarm-scenario/Swarm/Game/Scenario/Objective/Graph.hs
  src/swarm-topography/Swarm/Game/Location.hs
  src/swarm-tui/Swarm/TUI/Editor/Model.hs
  swarm.cabal
  weeder.toml
Labels: merge me

#2050 Add restore-keys logic for windows
  .github/workflows/haskell-ci-windows.yml
Labels: merge me

#2065 Fix string highlighting in vim
  editors/vim/swarm.vim
Labels: merge me

#2066 Put robot name in JSON
  src/swarm-engine/Swarm/Game/Robot/Concrete.hs
Labels: merge me

#2067 fix markdown link
  CONTRIBUTING.md
Labels: merge me

#2064 Use surveil in move tutorial
  data/scenarios/Tutorials/move.yaml
  data/scenarios/Tutorials/move_check.sw
  data/scenarios/Tutorials/move_surveil.sw
  data/scenarios/Tutorials/move_system.sw
  test/integration/Main.hs
Labels: merge me

#2071 Consolidate code in `WorldDescription`
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs
  src/swarm-scenario/Swarm/Game/State/Landscape.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Overlay.hs
  src/swarm-tui/Swarm/TUI/Editor/Palette.hs
  src/swarm-tui/Swarm/TUI/Editor/Util.hs
Labels: Z-Refactoring, merge me

#2074 Replace `TSyntax` with `Syntax` in a couple places, plus a bit of refactoring
  src/swarm-engine/Swarm/Game/Scenario/Scoring/CodeSize.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Initialize.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-lang/Swarm/Language/Parser.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  weeder.toml
Labels: merge me

#2077 Use and enforce Char as palette keys
  data/scenarios/Testing/_Validation/2077-palette-chars.yaml
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldPalette.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/ProtoCell.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-tui/Swarm/TUI/Editor/Palette.hs
Labels: Z-Refactoring, merge me

#2085 test and schema update for toplevel mask
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/2085-toplevel-mask.yaml
  data/schema/world.json
  test/integration/Main.hs
Labels: merge me

#2079 ensure non-overlapping mask char
  data/scenarios/Testing/_Validation/2077-mask-char.yaml
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure.hs
Labels: merge me

#2080 Add CLI option to start the game paused
  app/game/Main.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Runtime.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-scenario/Swarm/Game/State/Config.hs
  src/swarm-tournament/Swarm/Web/Tournament/Validate.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/Model.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  test/bench/Benchmark.hs
Labels: merge me

#2082 Clarify speed option help text
  app/game/Main.hs
Labels: merge me

#2084 remove pandoc dependency from main game
  app/doc/Main.hs
  scripts/gen/commands-matrix-data.sh
  src/swarm-doc/Swarm/Doc/Gen.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
  web/data/README.md
  web/data/commands.json
  web/index.html
  web/script/command-matrix.js
Labels: merge me

#2086 Structure placeholders in palette
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/2086-structure-palette.yaml
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Cell.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/ProtoCell.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-tui/Swarm/TUI/Editor/Palette.hs
  test/integration/Main.hs
Labels: merge me, Z-Developer Experience
