Repository swarm-game/swarm, pull requests merged in 2024-09, with the labels that each got.

#2130 Refactor App using standalone functions
  app/game/Swarm/App.hs
Labels: Z-Refactoring, merge me

#2132 Make cabal check happy with dependency bounds
  swarm.cabal
Labels: merge me

#2129 Avoid loading testing scenarios
  src/swarm-doc/Swarm/Doc/Pedagogy.hs
  src/swarm-engine/Swarm/Game/ScenarioInfo.hs
  src/swarm-engine/Swarm/Game/State/Runtime.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/SaveScenario.hs
  src/swarm-tui/Swarm/TUI/Model/DebugOption.hs
  src/swarm-tui/Swarm/TUI/Model/Menu.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  test/bench/Benchmark.hs
  test/integration/Main.hs
Labels: merge me, Z-Performance, CHANGELOG

#2139 Group modal dialog states into a record
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Main.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Robot.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/Model/Achievements.hs
  src/swarm-tui/Swarm/TUI/Model/Dialog.hs
  src/swarm-tui/Swarm/TUI/Model/Dialog/Goal.hs
  src/swarm-tui/Swarm/TUI/Model/Dialog/Popup.hs
  src/swarm-tui/Swarm/TUI/Model/Dialog/Structure.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/Model/UI.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/Objective.hs
  src/swarm-tui/Swarm/TUI/View/Popup.hs
  src/swarm-tui/Swarm/TUI/View/Robot.hs
  src/swarm-tui/Swarm/TUI/View/Structure.hs
  src/swarm-tui/Swarm/TUI/View/Util.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#2096 Pause on objective completion
  app/game/Main.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Runtime.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-scenario/Swarm/Game/State/Config.hs
  src/swarm-tournament/Swarm/Web/Tournament/Validate.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/Model.hs
  src/swarm-tui/Swarm/TUI/Model/DebugOption.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/Model/UI.hs
  test/bench/Benchmark.hs
Labels: merge me

#1553 Refactor capabilities
  data/entities.yaml
  data/scenarios/Challenges/Ranching/beekeeping.yaml
  data/scenarios/Challenges/Ranching/powerset.yaml
  data/scenarios/Challenges/Sliding Puzzles/3x3.yaml
  data/scenarios/Testing/1218-stride-command.yaml
  data/scenarios/Testing/508-capability-subset.yaml
  src/swarm-doc/Swarm/Doc/Wiki/Cheatsheet.hs
  src/swarm-engine/Swarm/Game/Exception.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-lang/Swarm/Language/Capability.hs
  src/swarm-lang/Swarm/Language/Requirements/Type.hs
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
  src/swarm-scenario/Swarm/Game/Device.hs
  src/swarm-tui/Swarm/TUI/Model/Event.hs
  src/swarm-tui/Swarm/TUI/View.hs
  swarm.cabal
  test/unit/TestRequirements.hs
Labels: merge me

#2143 cache scenario preview widget
  src/swarm-tui/Swarm/TUI/Model/Name.hs
  src/swarm-tui/Swarm/TUI/View.hs
Labels: T-UI, merge me, Z-Performance

#2144 Migrate to v8 of pixi.js, vendor the library
  web/play.html
  web/script/display.js
  web/script/fetch.js
  web/script/pixi.js
Labels: merge me

#2146 Watch for lodestone
  data/scenarios/Testing/562-lodestone.sw
  data/scenarios/Testing/562-lodestone.yaml
Labels: merge me

#2147 Make Rolex show time
  src/swarm-tui/Swarm/TUI/View.hs
Labels: merge me

#2046 Generate github release executables for macos
  .github/workflows/haskell-release.yml
Labels: merge me

#2127 Fix growable structure grids for multiple children with negative coordinates
  data/scenarios/Testing/1780-structure-merge-expansion/00-ORDER.txt
  data/scenarios/Testing/1780-structure-merge-expansion/sequential-placement.yaml
  data/test/standalone-topography/circle-and-crosses.yaml
  scripts/validate/issues-for-todos.sh
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Navigation/Portal.hs
  src/swarm-topography/Swarm/Game/Location.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Overlay.hs
  test/integration/Main.hs
  test/standalone-topography/src/Lib.hs
  test/standalone-topography/src/Main.hs
Labels: Bug, T-Testing, merge me

#2140 navigable robots table
  .hlint.yaml
  src/swarm-doc/Swarm/Doc/Wiki/Cheatsheet.hs
  src/swarm-engine/Swarm/Game/State/Initialize.hs
  src/swarm-topography/Swarm/Game/Universe.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Frame.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Main.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/REPL.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Robot.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/World.hs
  src/swarm-tui/Swarm/TUI/Controller/SaveScenario.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/Editor/Controller.hs
  src/swarm-tui/Swarm/TUI/Editor/Masking.hs
  src/swarm-tui/Swarm/TUI/Editor/View.hs
  src/swarm-tui/Swarm/TUI/Model.hs
  src/swarm-tui/Swarm/TUI/Model/Name.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/Model/UI.hs
  src/swarm-tui/Swarm/TUI/Model/UI/Gameplay.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/CellDisplay.hs
  src/swarm-tui/Swarm/TUI/View/Popup.hs
  src/swarm-tui/Swarm/TUI/View/Robot.hs
  src/swarm-tui/Swarm/TUI/View/Robot/Details.hs
  src/swarm-tui/Swarm/TUI/View/Robot/Type.hs
  src/swarm-tui/Swarm/TUI/View/Shared.hs
  src/swarm-tui/Swarm/TUI/View/Structure.hs
  src/swarm-tui/Swarm/TUI/View/Util.hs
  src/swarm-util/Swarm/Util.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
Labels: T-UI, merge me

#1285 Render contiguous boundaries
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1271-wall-boundaries.yaml
  src/swarm-scenario/Swarm/Game/Display.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/CellDisplay.hs
  test/integration/Main.hs
Labels: merge me

#2153 use wall rendering
  data/scenarios/Challenges/2048.yaml
  data/scenarios/Challenges/Sokoban/foresight.yaml
  data/scenarios/Challenges/bucket-brigade.yaml
  data/scenarios/Challenges/chess_horse.yaml
  data/scenarios/Challenges/dimsum.yaml
  data/scenarios/Challenges/hanoi.yaml
  data/scenarios/Challenges/ice-cream.yaml
  data/scenarios/Challenges/teleport.yaml
Labels: Z-Refactoring, merge me

#2150 Propagate origin displacements of child structures to parent
  data/scenarios/Testing/1780-structure-merge-expansion/00-ORDER.txt
  data/scenarios/Testing/1780-structure-merge-expansion/coordinate-offset-propagation.yaml
  data/scenarios/Testing/1780-structure-merge-expansion/sequential-placement.yaml
  data/scenarios/Testing/1780-structure-merge-expansion/simultaneous-north-and-west-offset.yaml
  data/test/standalone-topography/circle-and-crosses.yaml
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs
  src/swarm-topography/Swarm/Game/Location.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Area.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Overlay.hs
  test/integration/Main.hs
  test/unit/Main.hs
  test/unit/TestOverlay.hs
Labels: Bug, merge me

#2160 Use the new wall in move tutorial
  data/entities.yaml
  data/scenarios/Tutorials/move.yaml
  data/scenarios/Tutorials/move_check.sw
  data/scenarios/Tutorials/move_surveil.sw
  src/swarm-doc/Swarm/Doc/Gen.hs
Labels: merge me

#2162 Refactor: move ResourceLoading to swarm-util
  app/game/Main.hs
  src/swarm-engine/Swarm/Game/Achievement/Persistence.hs
  src/swarm-engine/Swarm/Game/ScenarioInfo.hs
  src/swarm-engine/Swarm/Game/State/Robot.hs
  src/swarm-engine/Swarm/Game/State/Runtime.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
  src/swarm-scenario/Swarm/Game/Recipe.hs
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/State/Config.hs
  src/swarm-scenario/Swarm/Game/Terrain.hs
  src/swarm-scenario/Swarm/Game/World/Load.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Model/KeyBindings.hs
  src/swarm-tui/Swarm/TUI/Model/UI.hs
  src/swarm-util/Swarm/ResourceLoading.hs
  swarm.cabal
Labels: merge me
