Repository swarm-game/swarm, pull requests merged in 2024-05, with the labels that each got.

#1815 biomes
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1642-biomes.yaml
  data/schema/entity.json
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
  src/swarm-scenario/Swarm/Game/Terrain.hs
  src/swarm-scenario/Swarm/Game/World.hs
  test/integration/Main.hs
Labels: merge me

#1819 Fix child robot privileges
  src/swarm-engine/Swarm/Game/Step/Const.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#1821 rename `doc-fragments` to `_doc-fragments`
  app/doc/Swarm/Doc/Schema/Render.hs
  data/scenarios/README.md
  data/scenarios/_doc-fragments/SCHEMA.md
  data/scenarios/_doc-fragments/base-robot.md
  data/scenarios/_doc-fragments/capabilities.md
  data/scenarios/_doc-fragments/cells.md
  data/scenarios/_doc-fragments/entity-properties.md
  data/scenarios/_doc-fragments/header.md
  data/schema/entity.json
  data/schema/robot.json
  data/schema/world.json
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
Labels: merge me

#1822 Recommend `cabal`
  CONTRIBUTING.md
  README.md
  feedback.yaml
  hie.cabal.yaml
  hie.stack.yaml
  scripts/autoplay-tutorials.sh
  scripts/build-game.sh
  scripts/gen/autopopulate-spellchecker.sh
  scripts/gen/schema-docs.sh
  scripts/play.sh
Labels: merge me

#1823 fix schema renderer
  app/doc/Swarm/Doc/Schema/Parse.hs
  app/doc/Swarm/Doc/Schema/Refined.hs
  app/doc/Swarm/Doc/Schema/Render.hs
  app/doc/Swarm/Doc/Schema/SchemaType.hs
  data/scenarios/_doc-fragments/SCHEMA.md
Labels: Bug, Z-Documentation, merge me

#1831 subdirectories for more scripts
  scripts/gen/preview-world-vscode.sh
  scripts/normalize/compare-format.sh
  scripts/test/benchmark-against-ancestor.sh
  scripts/test/benchmark-against-parent.sh
  scripts/test/run-benchmarks.sh
  scripts/test/run-tests.sh
Labels: Z-Refactoring, merge me

#1829 reorganize code in Assembly.hs
  data/schema/placement.json
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Placement.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
Labels: Z-Refactoring, merge me

#1832 Use 'Grid' newtype in more places
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs
Labels: Z-Refactoring, merge me

#1828 Support GHC 9.8, bump upper bounds, and update CI
  .github/workflows/haskell-ci.yml
  .github/workflows/hlint.yml
  .mergify.yml
  cabal.haskell-ci
  src/swarm-engine/Swarm/Game/Exception.hs
  src/swarm-engine/Swarm/Game/Robot/Concrete.hs
  src/swarm-lang/Swarm/Language/Direction.hs
  src/swarm-tournament/Swarm/Web/Tournament/Database/Query.hs
  swarm.cabal
Labels: merge me

#1833 structure placement order
  data/scenarios/Testing/1138-structures/sibling-precedence.yaml
  data/scenarios/Testing/1356-portals/portals-and-waypoints.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-placement-occlusion.yaml
  data/scenarios/Vignettes/roadway.yaml
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
Labels: merge me, Z-Developer Experience

#1834 Split out `swarm-doc` and `swarm-tui` sublibraries
  app/doc/Main.hs
  src/Swarm/TUI/Controller.hs
  src/swarm-doc/Swarm/Doc/Command.hs
  src/swarm-doc/Swarm/Doc/Gen.hs
  src/swarm-doc/Swarm/Doc/Keyword.hs
  src/swarm-doc/Swarm/Doc/Pedagogy.hs
  src/swarm-doc/Swarm/Doc/Schema/Arrangement.hs
  src/swarm-doc/Swarm/Doc/Schema/Parse.hs
  src/swarm-doc/Swarm/Doc/Schema/Refined.hs
  src/swarm-doc/Swarm/Doc/Schema/Render.hs
  src/swarm-doc/Swarm/Doc/Schema/SchemaType.hs
  src/swarm-doc/Swarm/Doc/Util.hs
  src/swarm-doc/Swarm/Doc/Wiki/Cheatsheet.hs
  src/swarm-doc/Swarm/Doc/Wiki/Matrix.hs
  src/swarm-doc/Swarm/Doc/Wiki/Util.hs
  src/swarm-engine/Swarm/Game/ScenarioInfo.hs
  swarm.cabal
Labels: merge me

#1840 actually move all `swarm-tui` modules into a `swarm-tui` subfolder
  src/swarm-tui/Swarm/TUI/Border.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/Editor/Controller.hs
  src/swarm-tui/Swarm/TUI/Editor/Json.hs
  src/swarm-tui/Swarm/TUI/Editor/Masking.hs
  src/swarm-tui/Swarm/TUI/Editor/Model.hs
  src/swarm-tui/Swarm/TUI/Editor/Palette.hs
  src/swarm-tui/Swarm/TUI/Editor/Util.hs
  src/swarm-tui/Swarm/TUI/Editor/View.hs
  src/swarm-tui/Swarm/TUI/Inventory/Sorting.hs
  src/swarm-tui/Swarm/TUI/Launch/Controller.hs
  src/swarm-tui/Swarm/TUI/Launch/Model.hs
  src/swarm-tui/Swarm/TUI/Launch/Prep.hs
  src/swarm-tui/Swarm/TUI/Launch/View.hs
  src/swarm-tui/Swarm/TUI/List.hs
  src/swarm-tui/Swarm/TUI/Model.hs
  src/swarm-tui/Swarm/TUI/Model/Goal.hs
  src/swarm-tui/Swarm/TUI/Model/Menu.hs
  src/swarm-tui/Swarm/TUI/Model/Name.hs
  src/swarm-tui/Swarm/TUI/Model/Repl.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/Model/Structure.hs
  src/swarm-tui/Swarm/TUI/Model/UI.hs
  src/swarm-tui/Swarm/TUI/Panel.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/Achievement.hs
  src/swarm-tui/Swarm/TUI/View/Attribute/Attr.hs
  src/swarm-tui/Swarm/TUI/View/Attribute/CustomStyling.hs
  src/swarm-tui/Swarm/TUI/View/Attribute/Util.hs
  src/swarm-tui/Swarm/TUI/View/CellDisplay.hs
  src/swarm-tui/Swarm/TUI/View/Logo.hs
  src/swarm-tui/Swarm/TUI/View/Objective.hs
  src/swarm-tui/Swarm/TUI/View/Structure.hs
  src/swarm-tui/Swarm/TUI/View/Util.hs
  swarm.cabal
Labels: merge me

#1841 Split the parser into submodules
  app/Main.hs
  src/swarm-lang/Swarm/Language/LSP.hs
  src/swarm-lang/Swarm/Language/LSP/Hover.hs
  src/swarm-lang/Swarm/Language/LSP/VarUsage.hs
  src/swarm-lang/Swarm/Language/Parse.hs
  src/swarm-lang/Swarm/Language/Parser.hs
  src/swarm-lang/Swarm/Language/Parser/Core.hs
  src/swarm-lang/Swarm/Language/Parser/Lex.hs
  src/swarm-lang/Swarm/Language/Parser/QQ.hs
  src/swarm-lang/Swarm/Language/Parser/Record.hs
  src/swarm-lang/Swarm/Language/Parser/Term.hs
  src/swarm-lang/Swarm/Language/Parser/Type.hs
  src/swarm-lang/Swarm/Language/Parser/Util.hs
  src/swarm-lang/Swarm/Language/Pipeline.hs
  src/swarm-lang/Swarm/Language/Pipeline/QQ.hs
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-lang/Swarm/Language/Syntax.hs
  src/swarm-lang/Swarm/Language/Text/Markdown.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  swarm.cabal
  test/unit/TestLSP.hs
  test/unit/TestLanguagePipeline.hs
  test/unit/TestParse.hs
Labels: merge me

#1837 Use sqlite and static binary
  app/tournament/Main.hs
  scripts/test/run-tests.sh
  src/swarm-tournament/Swarm/Web/Tournament.hs
  src/swarm-tournament/Swarm/Web/Tournament/Database/Query.hs
  src/swarm-tournament/Swarm/Web/Tournament/Type.hs
  swarm.cabal
  test/tournament-host/Main.hs
  tournament/README.md
  tournament/schema/schema-local.sql
  tournament/schema/swarm-sqlite-schema.sql
  tournament/scripts/database/dump-local-schema.sh
  tournament/scripts/database/recreate-local-database.sh
  tournament/scripts/demo/README.md
  tournament/scripts/demo/client/test-cases/local/good-submit.sh
  tournament/scripts/demo/client/test-cases/local/wrong-scenario-cached-solution.sh
  tournament/scripts/demo/server-docker.sh
  tournament/scripts/demo/server-native.sh
  tournament/scripts/deploy/redeploy-binary.sh
  tournament/scripts/deploy/redeploy-web-files.sh
  tournament/scripts/docker/Dockerfile
  tournament/scripts/docker/alpine/Dockerfile
  tournament/scripts/docker/aws-login.sh
  tournament/scripts/docker/build-image.sh
  tournament/scripts/docker/build-server-executable.sh
  tournament/scripts/docker/build-static-binary.sh
  tournament/scripts/docker/docker-prereqs.sh
  tournament/scripts/docker/local-docker-shell.sh
  tournament/scripts/docker/local-pg-credentials.env
  tournament/scripts/docker/redeploy-image.sh
Labels: merge me

#1849 Update sublibrary graph generation script & cabal description
  docs/image/sublibrary-graph.svg
  scripts/gen/render-sublibrary-dependencies.sh
  swarm.cabal
Labels: merge me

#1845 Insert parsed comments back into the AST and pretty-print with comments
  app/Main.hs
  src/swarm-lang/Swarm/Language/Elaborate.hs
  src/swarm-lang/Swarm/Language/Format.hs
  src/swarm-lang/Swarm/Language/LSP.hs
  src/swarm-lang/Swarm/Language/LSP/Hover.hs
  src/swarm-lang/Swarm/Language/Parser.hs
  src/swarm-lang/Swarm/Language/Parser/Comment.hs
  src/swarm-lang/Swarm/Language/Parser/QQ.hs
  src/swarm-lang/Swarm/Language/Parser/Type.hs
  src/swarm-lang/Swarm/Language/Parser/Util.hs
  src/swarm-lang/Swarm/Language/Pipeline/QQ.hs
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-lang/Swarm/Language/Syntax.hs
  src/swarm-lang/Swarm/Language/Value.hs
  src/swarm-scenario/Swarm/Game/World/Parse.hs
  src/swarm-util/Swarm/Util/Parse.hs
  swarm.cabal
  test/unit/TestLSP.hs
  test/unit/TestParse.hs
Labels: merge me, CHANGELOG

#1852 Split syntax module to reduce compilation time
  src/swarm-engine/Swarm/Game/Scenario/Topography/Navigation/Util.hs
  src/swarm-engine/Swarm/Game/Step/Util/Inspect.hs
  src/swarm-engine/Swarm/Game/Value.hs
  src/swarm-lang/Swarm/Language/Syntax.hs
  src/swarm-lang/Swarm/Language/Syntax/AST.hs
  src/swarm-lang/Swarm/Language/Syntax/Comments.hs
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
  src/swarm-lang/Swarm/Language/Syntax/Direction.hs
  src/swarm-lang/Swarm/Language/Syntax/Loc.hs
  src/swarm-lang/Swarm/Language/Syntax/Pattern.hs
  src/swarm-lang/Swarm/Language/Syntax/Util.hs
  src/swarm-scenario/Swarm/Game/Location.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Navigation/Portal.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Placement.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Recognition/Symmetry.hs
  src/swarm-tui/Swarm/TUI/View/Structure.hs
  swarm.cabal
Labels: merge me

#1853 Bump checkout and setup-node actions to v4
  .github/workflows/check_todos.yml
  .github/workflows/haskell-release.yml
  .github/workflows/scenario-schema.yml
  .github/workflows/vscode-ci.yml
  .github/workflows/vscode-publish.yml
  .github/workflows/yaml-normalization.yml
Labels: merge me

#1854 Help menu consistency fix
  src/swarm-tui/Swarm/TUI/View.hs
Labels: merge me

#1583 Require types to start with an uppercase letter
  data/entities.yaml
  data/scenarios/Challenges/2048.yaml
  data/scenarios/Challenges/Ranching/_beekeeping/queenbee.sw
  data/scenarios/Challenges/Ranching/_gated-paddock/fence-construction.sw
  data/scenarios/Challenges/Ranching/_gated-paddock/meandering-sheep.sw
  data/scenarios/Challenges/Ranching/_powerset/setup.sw
  data/scenarios/Challenges/Sliding Puzzles/_sliding-puzzle/maintainer.sw
  data/scenarios/Challenges/Sliding Puzzles/_sliding-puzzle/setup.sw
  data/scenarios/Challenges/Sliding Puzzles/_sliding-puzzle/solution.sw
  data/scenarios/Challenges/Sliding Puzzles/_sliding-puzzle/validate-board.sw
  data/scenarios/Challenges/_blender/apprehension-checker.sw
  data/scenarios/Challenges/_friend/cat.sw
  data/scenarios/Challenges/_hackman/ghost.sw
  data/scenarios/Challenges/_hanoi/hanoi-solution.sw
  data/scenarios/Challenges/_lights-out/assistant.sw
  data/scenarios/Challenges/_maypole/monitor.sw
  data/scenarios/Challenges/blender.yaml
  data/scenarios/Fun/GoL.yaml
  data/scenarios/Fun/_logo-burst/coordinator.sw
  data/scenarios/Fun/_logo-burst/drone.sw
  data/scenarios/Fun/_snake/snake.sw
  data/scenarios/Fun/horton.yaml
  data/scenarios/Testing/1721-walkability-whitelist-path-cache.yaml
  data/scenarios/Tutorials/bind2.yaml
  data/scenarios/Tutorials/conditionals.yaml
  data/scenarios/Tutorials/crash-secret.sw
  data/scenarios/Tutorials/def.yaml
  data/scenarios/Tutorials/farming.sw
  data/scenarios/Tutorials/lambda.yaml
  data/scenarios/Tutorials/types.yaml
  data/scenarios/Tutorials/world101.sw
  data/scenarios/Vignettes/_roadway/coordinator.sw
  data/scenarios/Vignettes/_roadway/drone.sw
  example/BFS-clear.sw
  example/cat.sw
  example/dfs.sw
  example/fact.sw
  example/list.sw
  example/multi-key-handler.sw
  example/pilotmode.sw
  example/wander.sw
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-lang/Swarm/Language/Parser/Lex.hs
  src/swarm-lang/Swarm/Language/Parser/Record.hs
  src/swarm-lang/Swarm/Language/Parser/Term.hs
  src/swarm-lang/Swarm/Language/Parser/Type.hs
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-lang/Swarm/Language/Types.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  test/bench/Benchmark.hs
  test/unit/TestEval.hs
  test/unit/TestLanguagePipeline.hs
  test/unit/TestPretty.hs
  test/unit/TestRepl.hs
Labels: merge me

#1851 Add `format --v0.5` option to port code from older syntax
  app/Main.hs
  src/swarm-lang/Swarm/Language/Format.hs
  src/swarm-lang/Swarm/Language/LSP.hs
  src/swarm-lang/Swarm/Language/LSP/Hover.hs
  src/swarm-lang/Swarm/Language/Parser.hs
  src/swarm-lang/Swarm/Language/Parser/Core.hs
  src/swarm-lang/Swarm/Language/Parser/Lex.hs
  src/swarm-lang/Swarm/Language/Parser/Term.hs
  src/swarm-lang/Swarm/Language/Parser/Type.hs
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  test/unit/TestLSP.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me, CHANGELOG

#1861 Handle backword kill word event in REPL
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
Labels: merge me

#1862 Minor update to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: merge me

#1826 structure grid expansion
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1780-structure-merge-expansion/00-ORDER.txt
  data/scenarios/Testing/1780-structure-merge-expansion/nonoverlapping-structure-merge.yaml
  data/scenarios/Testing/1780-structure-merge-expansion/root-map-expansion.yaml
  data/scenarios/Testing/1780-structure-merge-expansion/structure-composition.yaml
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Area.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Overlay.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldPalette.hs
  src/swarm-scenario/Swarm/Game/State/Landscape.hs
  src/swarm-scenario/Swarm/Game/World/Coords.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
  src/swarm-tui/Swarm/TUI/Editor/Controller.hs
  src/swarm-tui/Swarm/TUI/Editor/Palette.hs
  src/swarm-tui/Swarm/TUI/Editor/Util.hs
  swarm.cabal
  test/unit/Main.hs
  test/unit/TestOverlay.hs
Labels: merge me

#1817 spreadable plant growth
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1533-sow-command.yaml
  data/scenarios/Testing/1533-sow-seed-maturation.yaml
  data/schema/display.json
  data/schema/entity.json
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/swarm-engine/Swarm/Game/Step/Combustion.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-lang/Swarm/Language/Capability.hs
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-scenario/Swarm/Game/Display.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
  test/integration/Main.hs
Labels: merge me

#1866 Create and use lenses for ProcessedTerm and Module
  src/swarm-doc/Swarm/Doc/Pedagogy.hs
  src/swarm-engine/Swarm/Game/Scenario/Scoring/CodeSize.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-lang/Swarm/Language/LSP/Hover.hs
  src/swarm-lang/Swarm/Language/Module.hs
  src/swarm-lang/Swarm/Language/Pipeline.hs
  src/swarm-tournament/Swarm/Web/Tournament/Validate.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-web/Swarm/Web.hs
Labels: merge me

#1870 Update `FromJSON TickNumber` instance to match `ToJSON` instance
  src/swarm-engine/Swarm/Game/Tick.hs
  src/swarm-util/Swarm/Util/JSON.hs
  swarm.cabal
Labels: merge me

#1872 Move effect utils to `swarm-util`
  src/swarm-doc/Swarm/Doc/Gen.hs
  src/swarm-doc/Swarm/Doc/Pedagogy.hs
  src/swarm-doc/Swarm/Doc/Wiki/Cheatsheet.hs
  src/swarm-scenario/Swarm/Game/Failure.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
  src/swarm-util/Swarm/Util/Effect.hs
  swarm.cabal
  test/bench/Benchmark.hs
Labels: merge me

#1873 Represent types with applications of type constructors
  src/swarm-lang/Swarm/Effect/Unify/Fast.hs
  src/swarm-lang/Swarm/Effect/Unify/Naive.hs
  src/swarm-lang/Swarm/Language/Kindcheck.hs
  src/swarm-lang/Swarm/Language/Parser/Type.hs
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-lang/Swarm/Language/Types.hs
  swarm.cabal
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1875 validate subworld names of explicitly located robots
  data/scenarios/Testing/144-subworlds/subworld-shared-structures.yaml
  data/scenarios/Testing/_Validation/1875-robot-subworld-location.yaml
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/Universe.hs
  test/integration/Main.hs
Labels: merge me, Z-Developer Experience

#1876 Add `lens` entity and recipe for `detonator`
  data/entities.yaml
  data/recipes.yaml
Labels: merge me

#1877 Make log error messages ephemeral
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Log.hs
  src/swarm-tui/Swarm/TUI/View.hs
Labels: merge me

#1880 Always use parentheses when pretty-printing sum and product types
  src/swarm-lang/Swarm/Language/Pretty.hs
  test/unit/TestPretty.hs
Labels: merge me

#1881 Refactoring: Parse JSON using ApplicativeDo + RecordWildCards
  src/swarm-scenario/Swarm/Game/Display.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
  src/swarm-scenario/Swarm/Game/Recipe.hs
  src/swarm-scenario/Swarm/Game/Scenario/Objective.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Cell.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Navigation/Portal.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Navigation/Waypoint.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Placement.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-scenario/Swarm/Game/Universe.hs
  src/swarm-tournament/Swarm/Web/Auth.hs
Labels: merge me
