Repository swarm-game/swarm, pull requests merged in 2024-12, with the labels that each got.

#2216 Support a generic "original" payload in structure recognizer
  src/swarm-engine/Swarm/Game/ScenarioInfo.hs
  src/swarm-engine/Swarm/Game/State/Initialize.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util.hs
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/State/Landscape.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Grid.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Named.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Log.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Prep.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Registry.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Static.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Symmetry.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Tracking.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Type.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Main.hs
  src/swarm-tui/Swarm/TUI/Model/Dialog/Structure.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/CellDisplay.hs
  src/swarm-tui/Swarm/TUI/View/Structure.hs
  src/swarm-util/Swarm/Language/Syntax/Direction.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#2220 Add `TCAppL` and `TCAppR` typechecking stack frames, and remove `TCBind{L,R}`
  src/swarm-lang/Swarm/Language/Typecheck.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#2222 Add an extra `ghcup set` step to install instructions
  README.md
Labels: merge me

#2229 Fix shape recognition orientation edge case
  data/scenarios/Testing/1575-structure-recognizer/00-ORDER.txt
  data/scenarios/Testing/1575-structure-recognizer/2229-position-uniqueness-multiple-orientations.yaml
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Log.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Registry.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Tracking.hs
  test/integration/Main.hs
Labels: Bug, Z-Refactoring, merge me

#2224 New `read` command to act as partial inverse to `format`
  data/entities.yaml
  data/worlds/classic.world
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  editors/vscode/syntaxes/swarm.tmLanguage.yaml
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Arithmetic.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Value.hs
  src/swarm-lang/Swarm/Language/Elaborate.hs
  src/swarm-lang/Swarm/Language/LSP/Hover.hs
  src/swarm-lang/Swarm/Language/Parser/Record.hs
  src/swarm-lang/Swarm/Language/Parser/Value.hs
  src/swarm-lang/Swarm/Language/Syntax/AST.hs
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
  src/swarm-lang/Swarm/Language/Syntax/Pretty.hs
  src/swarm-lang/Swarm/Language/Syntax/Util.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-lang/Swarm/Language/Types.hs
  src/swarm-lang/Swarm/Language/Value.hs
  swarm.cabal
  test/unit/TestEval.hs
  weeder.toml
Labels: merge me

#2233 Update to allow GHC 9.10 and drop GHC 9.2
  .github/mergify.yml
  .github/workflows/haskell-ci.yml
  src/swarm-doc/Swarm/Doc/Pedagogy.hs
  src/swarm-lang/Swarm/Language/Parser/Term.hs
  src/swarm-lang/Swarm/Language/Value.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
  src/swarm-scenario/Swarm/Game/Recipe.hs
  src/swarm-scenario/Swarm/Game/World.hs
  src/swarm-scenario/Swarm/Game/World/Typecheck.hs
  src/swarm-tui/Swarm/TUI/Model/DebugOption.hs
  src/swarm-util/Swarm/Util.hs
  swarm.cabal
Labels: merge me

#2237 Validate hex colors in `FromJSON` instance
  .hlint.yaml
  data/scenarios/Testing/_Validation/2236-unparseable-attr-color.yaml
  src/swarm-scenario/Swarm/Game/Scenario/Style.hs
  src/swarm-tui/Swarm/TUI/View/Attribute/CustomStyling.hs
  src/swarm-web/Swarm/Web/Worldview.hs
Labels: merge me

#2241 Make custom entities override built-in entities
  data/scenarios/Challenges/Ranching/pied-piper.yaml
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/2239-custom-entity.yaml
  src/swarm-scenario/Swarm/Game/Entity.hs
Labels: merge me

#2247 generic cell modification
  src/swarm-engine/Swarm/Game/Step/Util.hs
  src/swarm-scenario/Swarm/Game/World.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Modify.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#2251 Add missing cases to var usage analysis
  data/test/language-snippets/warnings/unused-vars/lambda-with-annot.sw
  data/test/language-snippets/warnings/unused-vars/lambda-with-record-unused.sw
  data/test/language-snippets/warnings/unused-vars/lambda-with-record-used-abbrev.sw
  data/test/language-snippets/warnings/unused-vars/lambda-with-record-used.sw
  src/swarm-lang/Swarm/Language/LSP/VarUsage.hs
  test/unit/TestLSP.hs
Labels: merge me

#2248 Add combustion delay parameter
  data/scenarios/Testing/1355-combustion.yaml
  data/schema/combustion.json
  src/swarm-engine/Swarm/Game/Step/Combustion.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
Labels: merge me

#2242 Fix Semigroup EntityMap instance to update Capabilities map properly when there are overridden devices
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/2240-overridden-entity-capabilities.yaml
  src/swarm-scenario/Swarm/Game/Entity.hs
  test/integration/Main.hs
Labels: merge me
