Repository swarm-game/swarm, pull requests merged in 2024-11, with the labels that each got.

#2126 exterminator scenario
  data/scenarios/Challenges/Ranching/00-ORDER.txt
  data/scenarios/Challenges/Ranching/_pied-piper/rat.sw
  data/scenarios/Challenges/Ranching/_pied-piper/solution.sw
  data/scenarios/Challenges/Ranching/pied-piper.yaml
  scripts/gen/commands-wiki.sh
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Navigation/Portal.hs
  src/swarm-tui/Swarm/TUI/View/Attribute/Attr.hs
  src/swarm-tui/Swarm/TUI/View/Util.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#2207 update schema docs
  data/schema/placement.json
  data/schema/structure.json
  data/schema/world.json
Labels: Z-Documentation, merge me

#2209 refactor in preparation for new structure recognizer
  src/swarm-engine/Swarm/Game/State/Initialize.hs
  src/swarm-engine/Swarm/Game/Step/Util.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Log.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Prep.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Tracking.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Type.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#2211 Do requirements analysis for literal text argument to `use`
  src/swarm-lang/Swarm/Language/Requirements/Analysis.hs
  test/unit/TestRequirements.hs
Labels: merge me

#2191 Benchmark Dictionary implementation in Swarm
  example/recursive-containers.sw
Labels: merge me

#2202 Contexts that can be serialized + deserialized while retaining and explicitly representing sharing
  src/swarm-engine/Swarm/Game/CESK.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-lang/Swarm/Language/Context.hs
  src/swarm-lang/Swarm/Language/JSON.hs
  src/swarm-lang/Swarm/Language/Key.hs
  src/swarm-lang/Swarm/Language/Requirements/Type.hs
  src/swarm-lang/Swarm/Language/Syntax/AST.hs
  src/swarm-lang/Swarm/Language/Syntax/Comments.hs
  src/swarm-lang/Swarm/Language/Syntax/Loc.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-lang/Swarm/Language/Types.hs
  src/swarm-lang/Swarm/Language/Value.hs
  swarm.cabal
  test/unit/Main.hs
  test/unit/TestContext.hs
Labels: merge me

#2215 Don't insert extra close bracket when the cursor is already on top of one
  src/swarm-tui/Swarm/TUI/Controller.hs
Labels: merge me

#2212 ensure no overlaps in initial placement of recognized structures
  data/scenarios/Testing/1575-structure-recognizer/00-ORDER.txt
  data/scenarios/Testing/1575-structure-recognizer/2201-initial-recognition-overlap.yaml
  src/swarm-engine/Swarm/Game/State/Initialize.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-scenario/Swarm/Game/State/Landscape.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Area.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Grid.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Placement.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/ProtoCell.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Named.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Log.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Prep.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Registry.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Static.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Tracking.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Type.hs
  src/swarm-tui/Swarm/TUI/View/Structure.hs
  test/integration/Main.hs
Labels: Z-Refactoring, merge me
