Repository swarm-game/swarm, pull requests merged in 2024-08, with the labels that each got.

#2093 use structure palette markers in fishing scenario
  data/scenarios/Challenges/Ranching/fishing.yaml
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Cell.hs
Labels: merge me

#2048 Minor script fixes
  scripts/autoplay-tutorials.sh
  scripts/gen/haddocks.sh
  scripts/gen/preview-world-vscode.sh
  scripts/gen/render-sublibrary-dependencies.sh
  scripts/gen/schema-docs.sh
  scripts/normalize/all.sh
  scripts/normalize/cabal.sh
  scripts/normalize/code-format.sh
  scripts/normalize/compare-format.sh
  scripts/normalize/yaml.sh
  scripts/test/benchmark-against-ancestor.sh
  scripts/test/benchmark-against-parent.sh
  scripts/validate/issues-for-todos.sh
  scripts/validate/json-schemas.sh
Labels: merge me

#2095 Update the UI on game start
  app/game/Swarm/App.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Frame.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
Labels: merge me

#2094 Split debug options
  app/game/Main.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Main.hs
  src/swarm-tui/Swarm/TUI/Controller/SaveScenario.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/Model.hs
  src/swarm-tui/Swarm/TUI/Model/DebugOption.hs
  src/swarm-tui/Swarm/TUI/Model/Goal.hs
  src/swarm-tui/Swarm/TUI/Model/Menu.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/Model/UI.hs
  src/swarm-tui/Swarm/TUI/View.hs
  swarm.cabal
Labels: merge me, CHANGELOG

#2099 Demo standalone colored structures
  data/test/standalone-topography/rainbow.png
  data/test/standalone-topography/rainbow.yaml
  src/swarm-scenario/Swarm/Game/Entity/Cosmetic.hs
  src/swarm-scenario/Swarm/Game/Scenario/Style.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Rasterize.hs
  src/swarm-web/Swarm/Web/Worldview.hs
  swarm.cabal
  test/standalone-topography/src/Lib.hs
  test/standalone-topography/src/Main.hs
Labels: merge me

#2098 Replace `ReadableIORef` with IO
  app/game/Swarm/App.hs
  src/swarm-util/Swarm/Util/ReadableIORef.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
Labels: merge me

#2100 Put end on separate line when pretty printing definitions
  src/swarm-lang/Swarm/Language/Pretty.hs
Labels: merge me

#2104 Only check for escaped skolem variables among those just generated
  src/swarm-lang/Swarm/Language/Typecheck.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#2112 More generic structure recognition
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Initialize.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Path/Cache.hs
  src/swarm-engine/Swarm/Game/Step/Util.hs
  src/swarm-scenario/Swarm/Game/World/Modify.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Tracking.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Terraform.hs
  src/swarm-tui/Swarm/TUI/View/CellDisplay.hs
  src/swarm-tui/Swarm/TUI/View/Structure.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#2108 Reply to Web API run with result
  scripts/remote-repl.sh
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/Model.hs
  src/swarm-tui/Swarm/TUI/Model/WebCommand.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
Labels: merge me

#2120 Remove Brick dependency from Web
  app/game/Swarm/App.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
Labels: merge me

#2119 Do not show goal when ScenarioEnd is shown
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
Labels: merge me

#2122 Remove warp dependency from engine
  src/swarm-engine/Swarm/Game/State/Runtime.hs
  swarm.cabal
Labels: merge me

#2123 Move CHANGELOG to extra-doc-files
  swarm.cabal
Labels: merge me

#2115 better transparency handling for structure recognizer
  data/scenarios/Testing/1575-structure-recognizer/00-ORDER.txt
  data/scenarios/Testing/1575-structure-recognizer/1575-interior-entity-placement.yaml
  data/scenarios/Testing/1575-structure-recognizer/2115-encroaching-upon-exterior-transparent-cells.yaml
  data/scenarios/Testing/1575-structure-recognizer/2115-encroaching-upon-interior-transparent-cells.yaml
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Log.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Prep.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Tracking.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Type.hs
  test/integration/Main.hs
  weeder.toml
Labels: merge me

#2121 Move App version to app
  app/game/Swarm/Version.hs
  src/swarm-engine/Swarm/Game/State/Runtime.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Model.hs
  src/swarm-tui/Swarm/TUI/View.hs
  swarm.cabal
Labels: merge me
