Repository swarm-game/swarm, pull requests merged in 2024-06, with the labels that each got.

#1882 Fix FromJSON instance for better error msgs
  src/swarm-scenario/Swarm/Game/Entity.hs
Labels: merge me

#1865 Type synonyms
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  example/maybe.sw
  feedback.yaml
  src/swarm-engine/Swarm/Game/CESK.hs
  src/swarm-engine/Swarm/Game/Robot/Context.hs
  src/swarm-engine/Swarm/Game/Scenario/Scoring/GenericMetrics.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Path/Type.hs
  src/swarm-lang/Swarm/Effect/Unify.hs
  src/swarm-lang/Swarm/Effect/Unify/Fast.hs
  src/swarm-lang/Swarm/Effect/Unify/Naive.hs
  src/swarm-lang/Swarm/Language/Context.hs
  src/swarm-lang/Swarm/Language/Kindcheck.hs
  src/swarm-lang/Swarm/Language/LSP.hs
  src/swarm-lang/Swarm/Language/LSP/Hover.hs
  src/swarm-lang/Swarm/Language/Module.hs
  src/swarm-lang/Swarm/Language/Parser/Lex.hs
  src/swarm-lang/Swarm/Language/Parser/Term.hs
  src/swarm-lang/Swarm/Language/Parser/Type.hs
  src/swarm-lang/Swarm/Language/Pipeline.hs
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-lang/Swarm/Language/Requirement.hs
  src/swarm-lang/Swarm/Language/Syntax/AST.hs
  src/swarm-lang/Swarm/Language/Syntax/Pattern.hs
  src/swarm-lang/Swarm/Language/Syntax/Util.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-lang/Swarm/Language/Types.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-util/Swarm/Util/JSON.hs
  test/unit/TestLanguagePipeline.hs
  test/unit/TestPretty.hs
  test/unit/TestScoring.hs
Labels: merge me

#1836 topography sublibrary
  docs/image/sublibrary-graph.svg
  scripts/test/run-benchmarks.sh
  src/swarm-doc/Swarm/Doc/Keyword.hs
  src/swarm-engine/Swarm/Game/Scenario/Topography/Structure/Recognition/Tracking.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-engine/Swarm/Game/Step/Combustion.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Path/Finding.hs
  src/swarm-engine/Swarm/Game/Step/Util.hs
  src/swarm-lang/Swarm/Language/Parser/Lex.hs
  src/swarm-lang/Swarm/Language/Parser/Term.hs
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-lang/Swarm/Language/Requirement.hs
  src/swarm-lang/Swarm/Language/Syntax.hs
  src/swarm-lang/Swarm/Language/Value.hs
  src/swarm-scenario/Swarm/Game/Display.hs
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs
  src/swarm-topography/Swarm/Game/Location.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Area.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Navigation/Waypoint.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Placement.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Overlay.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Log.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Registry.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Symmetry.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Type.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Type.hs
  src/swarm-topography/Swarm/Game/Universe.hs
  src/swarm-tui/Swarm/TUI/Model/Structure.hs
  src/swarm-tui/Swarm/TUI/View/Structure.hs
  src/swarm-util/Swarm/Language/Syntax/Direction.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
  test/unit/TestCommand.hs
Labels: Z-Refactoring, merge me

#1890 Extend syntax highlighting in emacs + Vim config
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
Labels: merge me

#1902 More recipe for rubber
  data/recipes.yaml
Labels: merge me

#1903 Rebalance mine chances with metal drill
  data/recipes.yaml
Labels: merge me

#1905 Bring speedrun scenarios in line with classic scenario
  data/scenarios/Speedruns/curry.yaml
  data/scenarios/Speedruns/forester.yaml
  data/scenarios/Speedruns/mithril.yaml
Labels: merge me

#1894 Recursive types
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  example/omega.sw
  example/rectypes.sw
  src/swarm-lang/Swarm/Effect/Unify.hs
  src/swarm-lang/Swarm/Effect/Unify/Fast.hs
  src/swarm-lang/Swarm/Effect/Unify/Naive.hs
  src/swarm-lang/Swarm/Language/Capability.hs
  src/swarm-lang/Swarm/Language/Kindcheck.hs
  src/swarm-lang/Swarm/Language/Parser/Lex.hs
  src/swarm-lang/Swarm/Language/Parser/Type.hs
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-lang/Swarm/Language/Types.hs
  swarm.cabal
  test/unit/TestLanguagePipeline.hs
  test/unit/TestPretty.hs
Labels: merge me, CHANGELOG

#1906 Add device to provide `rectypes` capability
  data/entities.yaml
  data/recipes.yaml
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-lang/Swarm/Language/Pipeline.hs
  src/swarm-lang/Swarm/Language/Requirement.hs
Labels: merge me

#1912 pass tydefs from inferred module into requirements analysis
  src/swarm-lang/Swarm/Language/Pipeline.hs
Labels: merge me

#1913 Restructure hyperloop definition
  data/entities.yaml
Labels: merge me

#1908 minimize some To/FromJSON instances
  src/swarm-engine/Swarm/Game/CESK.hs
  src/swarm-engine/Swarm/Game/Step/Path/Type.hs
  src/swarm-lang/Swarm/Language/Context.hs
  src/swarm-lang/Swarm/Language/Syntax/AST.hs
  src/swarm-lang/Swarm/Language/Syntax/Comments.hs
  src/swarm-lang/Swarm/Language/Syntax/Loc.hs
  src/swarm-lang/Swarm/Language/Types.hs
  src/swarm-lang/Swarm/Language/Value.hs
  src/swarm-util/Swarm/Language/Syntax/Direction.hs
  src/swarm-util/Swarm/Util/JSON.hs
Labels: merge me

#1917 Fix Lazy IO opening too many files in integration tests
  src/swarm-util/Swarm/Util.hs
  test/integration/Main.hs
Labels: merge me

#1896 Fix non-exhaustive pattern in LSP
  src/swarm-lang/Swarm/Language/LSP/VarUsage.hs
Labels: merge me

#1915 Fix variable lookup during requirements analysis
  src/swarm-lang/Swarm/Language/Requirement.hs
  swarm.cabal
  test/unit/Main.hs
  test/unit/TestRequirements.hs
  test/unit/TestUtil.hs
Labels: merge me

#1919 Longer timeout for 479-atomic-race test
  test/integration/Main.hs
Labels: merge me

#1921 simplify parsing in WorldDescription
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs
Labels: Z-Refactoring, merge me

#1922 Don't set `it` variable when an exception was raised
  feedback.yaml
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Arithmetic.hs
  src/swarm-lang/Swarm/Language/Value.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Model.hs
Labels: merge me

#1927 Refactor some functions to use case
  src/swarm-engine/Swarm/Game/CESK.hs
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-lang/Swarm/Language/Value.hs
Labels: merge me

#1924 Make structures parseable independently of entity definitions
  data/test/standalone-topography/checkerboard.png
  data/test/standalone-topography/checkerboard.yaml
  data/test/standalone-topography/circle-and-crosses.png
  data/test/standalone-topography/circle-and-crosses.yaml
  scripts/normalize/all.sh
  scripts/validate/json-schemas.sh
  src/swarm-engine/Swarm/Game/Scenario/Topography/Structure/Recognition/Tracking.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Cell.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldPalette.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/ProtoCell.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Rasterize.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Registry.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Symmetry.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Recognition/Type.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Type.hs
  src/swarm-tui/Swarm/TUI/Editor/Palette.hs
  src/swarm-tui/Swarm/TUI/View/Structure.hs
  swarm.cabal
  test/standalone-topography/src/Lib.hs
  test/standalone-topography/src/Main.hs
Labels: Z-Refactoring, merge me

#1935 Enforce rectangular map grids
  data/scenarios/Testing/_Validation/1935-rectangular-area.yaml
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure.hs
  swarm.cabal
Labels: merge me, Z-Developer Experience

#1938 Enforce palette usage
  data/scenarios/Challenges/Ranching/powerset.yaml
  data/scenarios/Challenges/Sokoban/foresight.yaml
  data/scenarios/Challenges/ice-cream.yaml
  data/scenarios/Challenges/lights-out.yaml
  data/scenarios/Testing/1356-portals/portals-and-waypoints.yaml
  data/scenarios/Testing/144-subworlds/subworld-located-robots.yaml
  data/scenarios/Testing/144-subworlds/subworld-shared-structures.yaml
  data/scenarios/Testing/1536-custom-unwalkable-entities.yaml
  data/scenarios/Testing/1569-pathfinding-cache/1569-cache-invalidation-distance-limit.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-browse-structures.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-handle-overlapping.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-swap-structure.yaml
  data/scenarios/Testing/1681-pushable-entity.yaml
  data/scenarios/Testing/1780-structure-merge-expansion/root-map-expansion.yaml
  data/scenarios/Testing/1780-structure-merge-expansion/structure-composition.yaml
  data/scenarios/Testing/687-watch-command.yaml
  data/scenarios/Testing/836-pathfinding/836-no-path-exists1.yaml
  data/scenarios/Testing/_Validation/1938-palette-usage.yaml
  data/scenarios/Vignettes/roadway.yaml
  data/test/standalone-topography/checkerboard.yaml
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/Step/Util.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-scenario/Swarm/Game/State/Landscape.hs
  src/swarm-scenario/Swarm/Game/World.hs
  src/swarm-scenario/Swarm/Game/World/Gen.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
  src/swarm-scenario/Swarm/Util/Content.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Area.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-topography/Swarm/Game/World/Coords.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/Editor/Controller.hs
  src/swarm-tui/Swarm/TUI/Editor/Masking.hs
  src/swarm-tui/Swarm/TUI/Editor/Model.hs
  src/swarm-tui/Swarm/TUI/Editor/Util.hs
  src/swarm-tui/Swarm/TUI/Editor/View.hs
  src/swarm-tui/Swarm/TUI/Model/UI.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/CellDisplay.hs
  swarm.cabal
Labels: merge me, Z-Developer Experience

#1897 Pretty print code blocks according to widget size
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-tui/Swarm/TUI/View.hs
Labels: merge me

#1941 Remove duplicated test case
  test/unit/TestPretty.hs
Labels: merge me

#1942 Unit tests for prettyTextWidth
  test/unit/TestPretty.hs
Labels: merge me

#1936 Stop printing context after a definition.
  src/swarm-lang/Swarm/Language/Pretty.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1953 Automatically insert matching close brackets at REPL
  src/swarm-tui/Swarm/TUI/Controller.hs
Labels: merge me

#1950 Generate operators for all editors
  app/doc/Main.hs
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  editors/vscode/syntaxes/swarm.tmLanguage.yaml
  example/list.sw
  src/swarm-doc/Swarm/Doc/Gen.hs
  src/swarm-doc/Swarm/Doc/Keyword.hs
  test/integration/Main.hs
Labels: merge me

#1961 Get rid of unused packages
  swarm.cabal
Labels: merge me

#1963 Delete stack.yaml
  .gitignore
  hie.stack.yaml
  hie.yaml
  stack.yaml
Labels: merge me

#1957 Highlight error part in REPL
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Model/Repl.hs
  src/swarm-tui/Swarm/TUI/View.hs
Labels: merge me

#1949 Get rid of memoizing delay + switch to a strict store
  src/swarm-engine/Swarm/Game/CESK.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Arithmetic.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-lang/Swarm/Language/Elaborate.hs
  src/swarm-lang/Swarm/Language/LSP/Hover.hs
  src/swarm-lang/Swarm/Language/LSP/VarUsage.hs
  src/swarm-lang/Swarm/Language/Parser/Term.hs
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-lang/Swarm/Language/Requirements/Analysis.hs
  src/swarm-lang/Swarm/Language/Syntax/AST.hs
  src/swarm-lang/Swarm/Language/Syntax/Pattern.hs
  src/swarm-lang/Swarm/Language/Syntax/Util.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-lang/Swarm/Language/Value.hs
  test/unit/TestScoring.hs
Labels: merge me

#1968 Clear inventory search state when switching menus
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
Labels: merge me

#1973 Update copyright
  LICENSE
Labels: merge me

#1974 Add Windows build to CI
  .github/workflows/haskell-ci-windows.yml
  test/integration/Main.hs
Labels: merge me

#1972 Apply bindings before returning unification mismatch error
  src/swarm-lang/Swarm/Language/Typecheck.hs
  test/unit/TestLanguagePipeline.hs
Labels: merge me

#1971 Reset scroll position when switching modals
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/List.hs
Labels: merge me

#1975 Add hie.yaml to gitignore
  .gitignore
  hie.yaml
Labels: merge me

#1984 Add failing test case for #231
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/231-requirements/00-ORDER.txt
  data/scenarios/Testing/231-requirements/231-command-transformer-reqs.yaml
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#1983 Bring tutorial in line with #1957
  data/scenarios/Tutorials/type-errors.yaml
Labels: merge me

#1982 remove 'unGrid' accessor
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldDescription.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/WorldPalette.hs
  src/swarm-scenario/Swarm/Game/State/Landscape.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Area.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Overlay.hs
  src/swarm-tui/Swarm/TUI/Editor/Palette.hs
  src/swarm-tui/Swarm/TUI/Editor/Util.hs
Labels: Z-Refactoring, merge me

#1988 Fix world DSL coordinate bug
  data/scenarios/Challenges/Ranching/beekeeping.yaml
  data/scenarios/Challenges/gallery.yaml
  data/scenarios/Challenges/wave.yaml
  data/scenarios/Fun/horton.yaml
  data/scenarios/Testing/1320-world-DSL/00-ORDER.txt
  data/scenarios/Testing/1320-world-DSL/coords.yaml
  data/scenarios/Testing/1535-ping/1535-in-range.yaml
  data/scenarios/Testing/1535-ping/1535-out-of-range.yaml
  src/swarm-scenario/Swarm/Game/World/Interpret.hs
Labels: merge me

#1989 Fix world DSL `hash` primitive to depend on seed
  src/swarm-scenario/Swarm/Game/World/Compile.hs
  src/swarm-scenario/Swarm/Game/World/Interpret.hs
Labels: merge me

#1990 Add `imap` to world DSL, with examples
  data/scenarios/00-ORDER.txt
  data/scenarios/Testing/1320-world-DSL/00-ORDER.txt
  data/scenarios/Testing/1320-world-DSL/reflect.yaml
  data/scenarios/World Examples/00-ORDER.txt
  data/scenarios/World Examples/clearing.yaml
  data/scenarios/World Examples/rorschach.yaml
  data/scenarios/World Examples/stretch.yaml
  data/scenarios/World Examples/translate.yaml
  data/worlds/README.md
  src/swarm-scenario/Swarm/Game/World/Compile.hs
  src/swarm-scenario/Swarm/Game/World/Interpret.hs
  src/swarm-scenario/Swarm/Game/World/Parse.hs
  src/swarm-scenario/Swarm/Game/World/Syntax.hs
  src/swarm-scenario/Swarm/Game/World/Typecheck.hs
Labels: merge me

#1995 Remove grid overlay truncation behavior
  data/scenarios/Testing/1780-structure-merge-expansion/nonoverlapping-structure-merge.yaml
  data/scenarios/Testing/1780-structure-merge-expansion/root-map-expansion.yaml
  data/scenarios/Testing/1780-structure-merge-expansion/structure-composition.yaml
  data/test/standalone-topography/checkerboard.yaml
  data/test/standalone-topography/circle-and-crosses.yaml
  src/swarm-topography/Swarm/Game/Scenario/Topography/Placement.hs
  src/swarm-topography/Swarm/Game/Scenario/Topography/Structure/Assembly.hs
Labels: merge me

#1999 Change `meetAll` to return a list
  data/entities.yaml
  data/scenarios/Testing/920-meet.yaml
  data/scenarios/Tutorials/crash-secret.sw
  src/swarm-engine/Swarm/Game/CESK.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Value.hs
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
Labels: merge me

#1996 Remove duplicate transformers dependency
  swarm.cabal
Labels: merge me
