Repository swarm-game/swarm, pull requests merged in 2024-02, with the labels that each got.

#1757 Refactor `ObjectiveCompletion` to use lenses
  src/Swarm/TUI/Model/Goal.hs
  src/swarm-engine/Swarm/Game/Scenario/Objective/WinCheck.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-scenario/Swarm/Game/Scenario/Objective.hs
  src/swarm-scenario/Swarm/Game/Scenario/Objective/Graph.hs
  src/swarm-scenario/Swarm/Game/Scenario/Objective/Validation.hs
  src/swarm-util/Swarm/Util/Lens.hs
Labels: merge me

#1760 gallery scenario
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_gallery/setup.sw
  data/scenarios/Challenges/_gallery/solution.sw
  data/scenarios/Challenges/gallery.yaml
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-lang/Swarm/Language/Syntax.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
  test/integration/Main.hs
Labels: merge me, G-Scenarios

#1765 Dependency updates
  stack.yaml
  swarm.cabal
  test/integration/Main.hs
Labels: merge me

#1767 Decompose UIState record
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Util.hs
  src/Swarm/TUI/Editor/Controller.hs
  src/Swarm/TUI/Editor/Masking.hs
  src/Swarm/TUI/Editor/View.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/Model/UI.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/CellDisplay.hs
  src/Swarm/TUI/View/Util.hs
  src/swarm-web/Swarm/Web.hs
Labels: Z-Refactoring, merge me

#1766 Scenario description in goals dialog
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Objective.hs
Labels: merge me

#1771 decompose scenario record
  app/doc/Swarm/Doc/Gen.hs
  src/Swarm/Doc/Pedagogy.hs
  src/Swarm/Doc/Util.hs
  src/Swarm/TUI/Editor/Palette.hs
  src/Swarm/TUI/Launch/View.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/Util.hs
  src/swarm-engine/Swarm/Game/ScenarioInfo.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Center.hs
  src/swarm-scenario/Swarm/Game/State/Landscape.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
  src/swarm-web/Swarm/Web/Worldview.hs
Labels: Z-Refactoring, merge me

#1769 autoformat cabal file
  .github/workflows/normalize-cabal.yml
  scripts/normalize-cabal.sh
  swarm.cabal
Labels: merge me, Z-Developer Experience

#1628 fishing scenario
  data/scenarios/Challenges/Ranching/00-ORDER.txt
  data/scenarios/Challenges/Ranching/_fishing/hauler.sw
  data/scenarios/Challenges/Ranching/_fishing/shark.sw
  data/scenarios/Challenges/Ranching/_fishing/solution.sw
  data/scenarios/Challenges/Ranching/fishing.yaml
  test/integration/Main.hs
Labels: merge me, G-Scenarios

#1770 add scrollbar to scenario menu
  src/Swarm/TUI/View.hs
Labels: T-UI, merge me

#1774 Use entityAt instead of getContentAt
  src/swarm-engine/Swarm/Game/Step/Const.hs
Labels: merge me
