Repository swarm-game/swarm, pull requests merged in 2024-01, with the labels that each got.

#1697 web sublibrary
  app/Swarm/App.hs
  src/swarm-web/Swarm/Web.hs
  src/swarm-web/Swarm/Web/Worldview.hs
  swarm.cabal
Labels: merge me

#1700 move ReadableIORef to util sublibrary
  app/Swarm/App.hs
  src/swarm-util/Swarm/Util/ReadableIORef.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#1699 snake game
  data/scenarios/Fun/00-ORDER.txt
  data/scenarios/Fun/_snake/snake.sw
  data/scenarios/Fun/_snake/spawn.sw
  data/scenarios/Fun/snake.yaml
  test/integration/Main.hs
Labels: merge me, G-Scenarios

#1703 bump cabal-build version, fix haddock script
  scripts/view-haddocks.sh
  swarm.cabal
Labels: Z-Refactoring, merge me

#1704 swarm-lang sublibrary
  src/swarm-lang/Swarm/Language/Capability.hs
  src/swarm-lang/Swarm/Language/Context.hs
  src/swarm-lang/Swarm/Language/Direction.hs
  src/swarm-lang/Swarm/Language/Elaborate.hs
  src/swarm-lang/Swarm/Language/Key.hs
  src/swarm-lang/Swarm/Language/LSP.hs
  src/swarm-lang/Swarm/Language/LSP/Hover.hs
  src/swarm-lang/Swarm/Language/LSP/VarUsage.hs
  src/swarm-lang/Swarm/Language/Module.hs
  src/swarm-lang/Swarm/Language/Parse.hs
  src/swarm-lang/Swarm/Language/Parse/QQ.hs
  src/swarm-lang/Swarm/Language/Pipeline.hs
  src/swarm-lang/Swarm/Language/Pipeline/QQ.hs
  src/swarm-lang/Swarm/Language/Pretty.hs
  src/swarm-lang/Swarm/Language/Requirement.hs
  src/swarm-lang/Swarm/Language/Syntax.hs
  src/swarm-lang/Swarm/Language/Text/Markdown.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-lang/Swarm/Language/Typecheck/Unify.hs
  src/swarm-lang/Swarm/Language/Typed.hs
  src/swarm-lang/Swarm/Language/Types.hs
  src/swarm-lang/Swarm/Language/Value.hs
  swarm.cabal
Labels: Z-Refactoring, merge me

#1705 sort module list
  swarm.cabal
Labels: Z-Refactoring

#1707 fix color of trees in main logo
  src/Swarm/TUI/View/Logo.hs
Labels: merge me

#1708 update to LTS-21.25
  stack.yaml
Labels: merge me

#1710 Eliminate trailing whitespace in all scenarios
  data/scenarios/Challenges/Ranching/beekeeping.yaml
  data/scenarios/Challenges/Ranching/capture.yaml
  data/scenarios/Challenges/blender.yaml
  data/scenarios/Challenges/chess_horse.yaml
  data/scenarios/Challenges/hackman.yaml
  data/scenarios/Challenges/ice-cream.yaml
  data/scenarios/Challenges/lights-out.yaml
  data/scenarios/Challenges/maypole.yaml
  data/scenarios/Challenges/wave.yaml
  data/scenarios/Challenges/wolf-goat-cabbage.yaml
  data/scenarios/Fun/logo-burst.yaml
  data/scenarios/Testing/1218-stride-command.yaml
  data/scenarios/Testing/1356-portals/automatic-waypoint-patrol.yaml
  data/scenarios/Testing/1536-custom-unwalkable-entities.yaml
  data/scenarios/Testing/1569-pathfinding-cache/1569-cache-invalidation-distance-limit.yaml
  data/scenarios/Testing/1569-pathfinding-cache/1569-cache-invalidation-modes.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-ensure-disjoint.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-ensure-single-recognition.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-nested-structure-definition.yaml
  data/scenarios/Testing/1631-tags.yaml
  data/scenarios/Testing/1634-message-colors.yaml
  data/scenarios/Testing/795-prerequisite/795-prerequisite-mutually-exclusive.yaml
  data/scenarios/Tutorials/move.yaml
Labels: merge me

#1718 enforce scenario normalization
  .github/workflows/yaml-normalization.yml
  data/recipes.yaml
  scripts/normalize-all-scenarios.sh
  scripts/normalize-all-yaml.sh
Labels: merge me

#1720 autogenerated sublibrary diagram
  docs/image/sublibrary-graph.svg
  scripts/render-sublibrary-dependencies.sh
  swarm.cabal
Labels: Z-Documentation, merge me

#1688 Grant achievement for crafting a bitcoin
  src/swarm-engine/Swarm/Game/Step/Const.hs
Labels: merge me

#1727 Depend only on `vty-crossplatform`
  app/Swarm/App.hs
  stack.yaml
  swarm.cabal
Labels: merge me

#1722 Child robots only inherit their parent's `displayAttr`
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-util/Swarm/Util/Lens.hs
Labels: merge me

#1724 `infinite improbability drive` device enabling `teleport` command
  data/entities.yaml
  data/recipes.yaml
  data/worlds/classic.world
  src/swarm-engine/Swarm/Game/Entity.hs
  src/swarm-engine/Swarm/Game/Location.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
Labels: merge me

#1729 Use type family for robot CESK machine field
  app/doc/Swarm/Doc/Gen.hs
  src/Swarm/Doc/Util.hs
  src/swarm-engine/Swarm/Game/Robot.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Robot.hs
  src/swarm-engine/Swarm/Game/Step/Combustion.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  test/bench/Benchmark.hs
Labels: Z-Refactoring, merge me

#1731 Remove superfluous trobotContext lens
  src/swarm-engine/Swarm/Game/Robot.hs
  src/swarm-engine/Swarm/Game/State/Robot.hs
  src/swarm-engine/Swarm/Game/Step/Combustion.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  test/bench/Benchmark.hs
Labels: Z-Refactoring, merge me

#1732 Use type family for RobotContext field
  src/swarm-engine/Swarm/Game/Robot.hs
  src/swarm-engine/Swarm/Game/Robot/Context.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Combustion.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  swarm.cabal
  test/bench/Benchmark.hs
Labels: merge me

#1737 simplify infinite entity grabbing logic
  src/swarm-engine/Swarm/Game/Step/Const.hs
Labels: Z-Refactoring, C-Low Hanging Fruit, merge me

#1738 single entity update for swap
  src/swarm-engine/Swarm/Game/Step/Const.hs
Labels: merge me

#1587 workspace spelling dictionary
  .vscode/settings.json
  src/Swarm/TUI/Inventory/Sorting.hs
  src/swarm-lang/Swarm/Language/Syntax.hs
  src/swarm-lang/Swarm/Language/Text/Markdown.hs
Labels: merge me, Z-Developer Experience

#1742 move activity counts into swarm-engine
  src/Swarm/TUI/View.hs
  src/swarm-engine/Swarm/Game/Robot/Activity.hs
  src/swarm-engine/Swarm/Game/Robot/Concrete.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Combustion.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-scenario/Swarm/Game/Robot.hs
  swarm.cabal
  test/bench/Benchmark.hs
  test/integration/Main.hs
Labels: Z-Refactoring, merge me

#1743 Improve separation of engine and scenario sublibraries
  src/swarm-engine/Swarm/Game/Robot/Concrete.hs
  src/swarm-engine/Swarm/Game/Scenario/Scoring/Best.hs
  src/swarm-engine/Swarm/Game/Scenario/Scoring/CodeSize.hs
  src/swarm-engine/Swarm/Game/Scenario/Scoring/ConcreteMetrics.hs
  src/swarm-engine/Swarm/Game/Scenario/Scoring/GenericMetrics.hs
  src/swarm-engine/Swarm/Game/Scenario/Status.hs
  src/swarm-engine/Swarm/Game/ScenarioInfo.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-engine/Swarm/Game/Tick.hs
  src/swarm-engine/Swarm/Log.hs
  src/swarm-scenario/Swarm/Game/Robot.hs
  swarm.cabal
  test/integration/Main.hs
  test/unit/TestNotification.hs
Labels: Z-Refactoring, merge me

#1658 Render command matrix
  app/doc/Main.hs
  app/doc/Swarm/Doc/Schema/Render.hs
  app/doc/Swarm/Doc/Wiki/Cheatsheet.hs
  app/doc/Swarm/Doc/Wiki/Matrix.hs
  app/doc/Swarm/Doc/Wiki/Util.hs
  src/Swarm/Doc/Command.hs
  src/swarm-lang/Swarm/Language/Syntax.hs
  src/swarm-lang/Swarm/Language/Syntax/CommandMetadata.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
  web/command-matrix.html
  web/script/command-matrix.js
  web/style/command-matrix.css
  web/style/tablesort.css
Labels: merge me

#1744 apply hlint 3.8 suggestions
  app/Main.hs
  src/swarm-engine/Swarm/Game/Step/Path/Cache.hs
  src/swarm-lang/Swarm/Language/Parse.hs
  src/swarm-lang/Swarm/Language/Text/Markdown.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Recognition/Precompute.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Structure/Recognition/Type.hs
Labels: Z-Refactoring, merge me

#1746 Remove Benchmark dependence on AppState and TUI
  app/Swarm/App.hs
  scripts/benchmark-against-parent.sh
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/View.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Runtime.hs
  src/swarm-engine/Swarm/Version.hs
  swarm.cabal
  test/bench/Benchmark.hs
  test/integration/Main.hs
  test/unit/TestPedagogy.hs
  test/unit/TestRecipeCoverage.hs
Labels: Z-Refactoring, merge me

#1747 volume command
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/1747-volume-command.yaml
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  editors/vscode/syntaxes/swarm.tmLanguage.json
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Flood.hs
  src/swarm-lang/Swarm/Language/Capability.hs
  src/swarm-lang/Swarm/Language/Syntax.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  swarm.cabal
  test/integration/Main.hs
Labels: merge me, L-Commands

#1749 autopopulate spellchecker
  .vscode/settings.json
  cspell.json
  scripts/reformat-code.sh
  scripts/spellcheck/autopopulate-spellchecker.sh
  scripts/spellcheck/split-module-names.hs
Labels: merge me, Z-Developer Experience

#1752 extract scene renderer to its own binary
  app/Main.hs
  app/doc/Swarm/Doc/Gen.hs
  app/scene/Main.hs
  src/Swarm/TUI/Controller.hs
  src/Swarm/TUI/Controller/Util.hs
  src/Swarm/TUI/Editor/Controller.hs
  src/Swarm/TUI/Launch/Prep.hs
  src/Swarm/TUI/Model.hs
  src/Swarm/TUI/Model/Menu.hs
  src/Swarm/TUI/Model/StateUpdate.hs
  src/Swarm/TUI/View.hs
  src/Swarm/TUI/View/CellDisplay.hs
  src/swarm-engine/Swarm/Game/ScenarioInfo.hs
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Runtime.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Combustion.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Center.hs
  src/swarm-scenario/Swarm/Game/State/Config.hs
  src/swarm-scenario/Swarm/Game/State/Landscape.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
  src/swarm-scenario/Swarm/Util/Content.hs
  src/swarm-web/Swarm/Web/Worldview.hs
  swarm.cabal
  test/bench/Benchmark.hs
  test/unit/TestUtil.hs
Labels: Z-Refactoring, merge me

#1751 check achievement robot requirements
  src/swarm-engine/Swarm/Game/Achievement/Description.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-scenario/Swarm/Game/Achievement/Definitions.hs
Labels: merge me

#1754 tweak benchmarks
  .gitignore
  scripts/benchmark-against-parent.sh
  scripts/run-benchmarks.sh
  swarm.cabal
  test/bench/Benchmark.hs
Labels: merge me, Z-Performance

#1755 simplify spellchecker words script
  scripts/autopopulate-spellchecker.sh
  scripts/spellcheck/split-module-names.hs
Labels: merge me

#1756 preview rendered world with inotify
  app/scene/Main.hs
  scripts/preview-world-vscode.sh
  src/swarm-scenario/Swarm/Game/Scenario/Topography/Area.hs
  src/swarm-scenario/Swarm/Game/World/Render.hs
Labels: merge me, Z-Developer Experience
