Repository swarm-game/swarm, pull requests merged in 2025-07, with the labels that each got.

#2514 Make entities in bind2 tutorial known
  data/scenarios/Tutorials/bind2.yaml
Labels: merge me

#2520 Move view center state to internal module
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Initialize.hs
  src/swarm-engine/Swarm/Game/State/Robot.hs
  src/swarm-engine/Swarm/Game/State/ViewCenter/Internal.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Combustion.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-engine/Swarm/Game/Step/Util/Inspect.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Main.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/World.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/Robot.hs
  src/swarm-tui/Swarm/TUI/View/Static.hs
  src/swarm-web/Swarm/Web.hs
  swarm.cabal
  test/unit/TestNotification.hs
  test/unit/TestUtil.hs
Labels: merge me

#2515 View chunk caching for fast world drawing
  .hlint.yaml
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Redraw.hs
  src/swarm-engine/Swarm/Game/State/Robot.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Combustion.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-scenario/Swarm/Util/Content.hs
  src/swarm-topography/Swarm/Game/Location.hs
  src/swarm-topography/Swarm/Game/Universe.hs
  src/swarm-topography/Swarm/Game/World/Coords.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Frame.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Main.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/World.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/Editor/Controller.hs
  src/swarm-tui/Swarm/TUI/Model/Name.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/Model/UI/Gameplay.hs
  src/swarm-tui/Swarm/TUI/Model/ViewChunk.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-util/Swarm/Util.hs
  swarm.cabal
  test/unit/Main.hs
  test/unit/TestViewChunk.hs
Labels: T-UI, merge me, Z-Performance, CHANGELOG

#2532 Get rid of a use of `Map.!` in `Swarm.Language.Typecheck`
  .hlint.yaml
  src/swarm-lang/Swarm/Language/Typecheck.hs
Labels: merge me

#2535 Redraw world when static changes
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-engine/Swarm/Game/State/Range.hs
  src/swarm-engine/Swarm/Game/State/Redraw.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/View/Static.hs
  swarm.cabal
Labels: merge me

#2546 Update CI
  .github/workflows/haskell-ci-windows.yml
  .github/workflows/haskell-ci.yml
Labels: merge me

#2547 Auto-insert matching close quotes
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Model/Repl.hs
Labels: merge me, CHANGELOG

#2549 Use `T.intercalate` instead of `T.unlines` so we don't add trailing newline to REPL text
  src/swarm-tui/Swarm/TUI/Model/Repl.hs
Labels: merge me

#2551 Ignore `Tab` key in inventory search mode
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Robot.hs
Labels: merge me

#2538 Watch for robots as well
  data/scenarios/Challenges/Ranching/_capture/opponent.sw
  data/scenarios/Challenges/Ranching/_capture/solution.sw
  data/scenarios/Challenges/_gopher/gopher.sw
  data/scenarios/Tutorials/debug-hint.sw
  src/swarm-engine/Swarm/Game/State/Robot.hs
  src/swarm-engine/Swarm/Game/State/RobotNaming.hs
  src/swarm-engine/Swarm/Game/State/Robots/Internal.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
  swarm.cabal
Labels: merge me

#2553 Include combustion products in recipe graph analysis
  data/entities.yaml
  src/swarm-scenario/Swarm/Game/Recipe/Graph.hs
  test/integration/TestRecipeCoverage.hs
Labels: merge me

#2554 Rename `Win` to `win` in tutorial scenarios
  data/scenarios/Tutorials/debug-hint.sw
  data/scenarios/Tutorials/debug.yaml
  data/scenarios/Tutorials/type-errors.yaml
  data/scenarios/Tutorials/types.yaml
Labels: merge me
