Repository swarm-game/swarm, pull requests merged in 2025-01, with the labels that each got.

#2256 Don't update scenario completion stats after scenario completion
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-tui/Swarm/TUI/Controller/SaveScenario.hs
Labels: merge me

#2245 Add `print` + `erase` commands, and a challenge scenario showing off `print`
  data/entities.yaml
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_telephone/judge.sw
  data/scenarios/Challenges/_telephone/photocopier.sw
  data/scenarios/Challenges/_telephone/shuttle.sw
  data/scenarios/Challenges/_telephone/solution.sw
  data/scenarios/Challenges/telephone.yaml
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  editors/vscode/syntaxes/swarm.tmLanguage.yaml
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-lang/Swarm/Language/Parser/Value.hs
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
  src/swarm-tui/Swarm/TUI/View.hs
  test/integration/Main.hs
  test/unit/TestEval.hs
Labels: merge me, CHANGELOG

#2254 Make `halt`ed robots immediately wake up
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/2253-halt-waiting.yaml
  src/swarm-engine/Swarm/Game/Step/Const.hs
  test/integration/Main.hs
Labels: merge me

#2262 only meet interactive robots
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-scenario/Swarm/Game/Robot.hs
Labels: merge me

#2249 Counting flowers
  data/scenarios/Challenges/00-ORDER.txt
  data/scenarios/Challenges/_flower-count/judge.sw
  data/scenarios/Challenges/_flower-count/solution.sw
  data/scenarios/Challenges/flower-count.yaml
  test/integration/Main.hs
Labels: merge me, CHANGELOG

#2260 Make `structures`, `waypoints`, and `tagmembers` commands return lists
  data/entities.yaml
  data/scenarios/Challenges/Ranching/_beekeeping/queenbee.sw
  data/scenarios/Challenges/Ranching/_fishing/hauler.sw
  data/scenarios/Challenges/Ranching/_fishing/solution.sw
  data/scenarios/Challenges/Ranching/beekeeping.yaml
  data/scenarios/Challenges/Ranching/fishing.yaml
  data/scenarios/Challenges/_dna/lab.sw
  data/scenarios/Challenges/_dna/solution.sw
  data/scenarios/Challenges/_gallery/setup.sw
  data/scenarios/Challenges/dna.yaml
  data/scenarios/Challenges/gallery.yaml
  data/scenarios/Challenges/pack-tetrominoes.yaml
  data/scenarios/Challenges/word-search.yaml
  data/scenarios/Testing/1356-portals/_automatic-waypoint-patrol/program.sw
  data/scenarios/Testing/1575-structure-recognizer/1575-bounding-box-overlap.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-browse-structures.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-construction-count.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-ensure-disjoint.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-ensure-single-recognition.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-floorplan-command.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-handle-overlapping.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-interior-entity-placement.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-nested-structure-definition.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-overlapping-tiebreaker-by-largest.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-overlapping-tiebreaker-by-location.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-placement-occlusion.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-remove-structure.yaml
  data/scenarios/Testing/1575-structure-recognizer/1575-swap-structure.yaml
  data/scenarios/Testing/1575-structure-recognizer/1644-rotated-preplacement-recognition.yaml
  data/scenarios/Testing/1575-structure-recognizer/1644-rotated-recognition.yaml
  data/scenarios/Testing/1575-structure-recognizer/2115-encroaching-upon-exterior-transparent-cells.yaml
  data/scenarios/Testing/1575-structure-recognizer/2115-encroaching-upon-interior-transparent-cells.yaml
  data/scenarios/Testing/1575-structure-recognizer/2201-initial-recognition-overlap.yaml
  data/scenarios/Testing/1575-structure-recognizer/2201-piecewise-lines.yaml
  data/scenarios/Testing/1575-structure-recognizer/2201-preclude-overlapping-recognition.yaml
  data/scenarios/Testing/1575-structure-recognizer/2229-position-uniqueness-multiple-orientations.yaml
  data/scenarios/Testing/1631-tags.yaml
  data/scenarios/Testing/836-pathfinding/_836-automatic-waypoint-navigation/patrol.sw
  data/scenarios/Testing/836-pathfinding/_836-automatic-waypoint-navigation/rabbit.sw
  editors/emacs/swarm-mode.el
  editors/vim/swarm.vim
  editors/vscode/syntaxes/swarm.tmLanguage.yaml
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Value.hs
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
Labels: merge me

#2271 Evaluate argument to `instant`/`atomic` atomically, as a special case
  data/scenarios/Challenges/_gallery/setup.sw
  data/scenarios/Testing/00-ORDER.txt
  data/scenarios/Testing/2270-instant-defs.yaml
  src/swarm-engine/Swarm/Game/Step.hs
  test/integration/Main.hs
Labels: merge me

#2268 nested lens usage refactor (part 1)
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Frame.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Main.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/REPL.hs
  src/swarm-tui/Swarm/TUI/Editor/Controller.hs
  src/swarm-tui/Swarm/TUI/Editor/View.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/Util.hs
Labels: Z-Refactoring, merge me

#2273 Use forM_/mapM_
  src/swarm-doc/Swarm/Doc/Schema/Refined.hs
  src/swarm-engine/Swarm/Game/ScenarioInfo.hs
  src/swarm-engine/Swarm/Game/State/Robot.hs
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
  src/swarm-scenario/Swarm/Game/Scenario.hs
  src/swarm-scenario/Swarm/Game/Scenario/Objective/Validation.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/SaveScenario.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/Editor/Controller.hs
  test/integration/Main.hs
  test/unit/TestOverlay.hs
Labels: Z-Refactoring, merge me

#2277 bump timeout for gallery scenario
  test/integration/Main.hs
Labels: T-Testing, merge me

#2278 Warn the user when debugging options are on
  src/swarm-tui/Swarm/TUI/Model/Dialog/Popup.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/View/Popup.hs
Labels: merge me

#2289 render goals graph
  scripts/gen/goals-graph.sh
  src/swarm-web/Swarm/Web.hs
  src/swarm-web/Swarm/Web/GraphRender.hs
  swarm.cabal
Labels: merge me, Z-Developer Experience

#2290 move gen scripts subfolders
  scripts/gen/doc/commands-matrix-data.sh
  scripts/gen/doc/commands-wiki.sh
  scripts/gen/doc/haddocks.sh
  scripts/gen/doc/schema-docs.sh
  scripts/gen/img/preview-world-vscode.sh
  scripts/gen/img/render-sublibrary-dependencies.sh
  scripts/gen/live/README.md
  scripts/gen/live/goals-graph.sh
Labels: merge me, Z-Developer Experience

#2293 Make FPS toggle and "recenter view" into global events
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/Main.hs
  src/swarm-tui/Swarm/TUI/Controller/EventHandlers/World.hs
  src/swarm-tui/Swarm/TUI/Model/Event.hs
  src/swarm-tui/Swarm/TUI/View.hs
Labels: merge me

#2295 Disallow `IntMap.!`
  .hlint.yaml
  src/swarm-engine/Swarm/Game/State.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
Labels: merge me

#2299 Minimize list of required device sets in error message
  src/swarm-engine/Swarm/Game/Exception.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-util/Swarm/Util.hs
Labels: merge me
