Repository swarm-game/swarm, pull requests merged in 2025-05, with the labels that each got.

#2423 Dependency updates
  .github/mergify.yml
  .github/workflows/haskell-ci.yml
  src/swarm-engine/Swarm/Game/Step.hs
  src/swarm-engine/Swarm/Game/Step/Arithmetic.hs
  src/swarm-engine/Swarm/Game/Step/Combustion.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-engine/Swarm/Game/Step/Util.hs
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-lang/Swarm/Language/Context.hs
  src/swarm-lang/Swarm/Language/Syntax/Comments.hs
  src/swarm-lang/Swarm/Language/Syntax/Constants.hs
  src/swarm-lang/Swarm/Language/Syntax/Pattern.hs
  src/swarm-scenario/Swarm/Game/World/Interpret.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/Model/Repl.hs
  src/swarm-util/Swarm/Language/Syntax/Direction.hs
  src/swarm-util/Swarm/Util.hs
  swarm.cabal
  test/standalone-topography/src/Main.hs
Labels: merge me

#2424 Add Swiss Army Robot achievement for equipping all craftable devices in classic game
  src/swarm-doc/Swarm/Doc/Gen.hs
  src/swarm-doc/Swarm/Doc/Util.hs
  src/swarm-engine/Swarm/Game/Achievement/Description.hs
  src/swarm-engine/Swarm/Game/Scenario/Status.hs
  src/swarm-engine/Swarm/Game/State/Initialize.hs
  src/swarm-engine/Swarm/Game/State/Substate.hs
  src/swarm-engine/Swarm/Game/Step/Const.hs
  src/swarm-scenario/Swarm/Game/Achievement/Definitions.hs
  src/swarm-scenario/Swarm/Game/Entity.hs
  src/swarm-scenario/Swarm/Game/Recipe/Graph.hs
  src/swarm-scenario/Swarm/Game/Robot.hs
  swarm.cabal
  test/integration/TestRecipeCoverage.hs
Labels: merge me

#2419 More dialog logic simplification
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
  src/swarm-tui/Swarm/TUI/Controller/Util.hs
  src/swarm-tui/Swarm/TUI/View/Util.hs
Labels: Z-Refactoring, merge me

#2436 Add some optional goals to the classic scenario
  data/entities.yaml
  data/scenarios/classic.yaml
Labels: merge me

#2441 Throw proper exceptions when encountering unbound user-defined types in `expandTydef` + related functions
  src/swarm-lang/Swarm/Effect/Unify/Fast.hs
  src/swarm-lang/Swarm/Language/Kindcheck.hs
  src/swarm-lang/Swarm/Language/Requirements/Analysis.hs
  src/swarm-lang/Swarm/Language/Typecheck.hs
  src/swarm-lang/Swarm/Language/Types.hs
  src/swarm-util/Swarm/Failure.hs
Labels: merge me

#2442 Restore the fix for robot modal leak by only rendering when visible
  src/swarm-tui/Swarm/TUI/Controller/UpdateUI.hs
Labels: merge me

#2445 Ignore profiling outputs
  .gitignore
Labels: merge me

#2444 Update debug scenario and robot detail modal
  data/scenarios/Tutorials/00-ORDER.txt
  data/scenarios/Tutorials/crash-secret.sw
  data/scenarios/Tutorials/debug-hint.sw
  data/scenarios/Tutorials/debug.yaml
  src/swarm-engine/Swarm/Game/Step/Util/Command.hs
  src/swarm-engine/Swarm/Game/Tick.hs
  src/swarm-tui/Swarm/TUI/View.hs
  src/swarm-tui/Swarm/TUI/View/Robot/Details.hs
  test/integration/Main.hs
Labels: merge me, CHANGELOG

#2454 Use Brick.Animation to implement popup notifications
  app/game/Swarm/App.hs
  src/swarm-engine/Swarm/Game/Popup.hs
  src/swarm-tui/Swarm/TUI/Controller.hs
  src/swarm-tui/Swarm/TUI/Model.hs
  src/swarm-tui/Swarm/TUI/Model/StateUpdate.hs
  src/swarm-tui/Swarm/TUI/View/Popup.hs
  test/integration/Main.hs
Labels: merge me
